'use client';
import {useEffect,useRef,useState} from 'react';
import {Printer,Pause} from 'lucide-react';
import {connectKitchenPrinter,printerAvailable,printerSupported,printKitchenReceipt,printerPlatform,disconnectKitchenPrinter} from '@/lib/kitchen-printer';
import {toast} from 'sonner';
import {bleSupported,connectBlePrinter,bleDiagnostic} from '@/lib/ble-printer';

export default function AutomaticKitchenPrinter({authorization,demo,connectionOnly=false}:{authorization:string;demo:boolean;connectionOnly?:boolean}){
 const [expanded,setExpanded]=useState(false),[enabled,setEnabled]=useState(false),[connected,setConnected]=useState(false),[supported,setSupported]=useState(false),[starting,setStarting]=useState(false),[platform,setPlatform]=useState('desktop'),[browserInfo,setBrowserInfo]=useState(''),[message,setMessage]=useState('Conecte a impressora e confira o papel de teste antes de imprimir pedidos.');
 const [ble,setBle]=useState(false),[diagnostic,setDiagnostic]=useState(''),[service,setService]=useState(''),[characteristic,setCharacteristic]=useState('');
 const device=useRef(''),since=useRef(''),inFlight=useRef(false);
 // Browser capabilities are unavailable during SSR; detect once after hydration.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{device.current=crypto.randomUUID();setSupported(printerSupported());setBle(bleSupported());setConnected(printerAvailable());setPlatform(printerPlatform(navigator.userAgent,navigator.maxTouchPoints));setBrowserInfo(/SamsungBrowser/i.test(navigator.userAgent)?'Samsung Internet':/EdgA/i.test(navigator.userAgent)?'Edge Android':/Chrome\/(\d+)/.exec(navigator.userAgent)?.[0].replace('/',' ')||'Navegador sem identificação Chrome');const timer=setInterval(()=>setConnected(printerAvailable()),1500);return()=>clearInterval(timer)},[]);
 useEffect(()=>{
  if(connectionOnly||!enabled||!authorization||demo)return;
  let disposed=false;
  async function request(body:Record<string,unknown>){const r=await fetch('/api/local-print',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${authorization}`},body:JSON.stringify({...body,deviceId:device.current}),signal:AbortSignal.timeout(12000)});const data=await r.json() as {error?:string;job?:{id:string;content:string}|null};if(!r.ok)throw Error(data.error||'Falha na conexão.');return data}
  async function tick(){
   if(disposed||document.hidden||inFlight.current)return;
   if(!printerAvailable()){setMessage('Impressora desconectada. Reconecte para continuar.');return}
   inFlight.current=true;const claimToken=crypto.randomUUID();
   try{
    const {job}=await request({type:'claim',claimToken,since:since.current});
    if(job){
     setMessage('Enviando comanda…');
     let success=false;
     try{await printKitchenReceipt(job.id,job.content);success=true}finally{await request({type:'finish',claimToken,jobId:job.id,success})}
     if(!disposed)setMessage('Comanda enviada. Aguardando o próximo pedido.');
    }
   }catch(e){if(!disposed){setEnabled(false);setMessage((e as Error).message);toast.error('Impressão pausada. Confira a conexão e o papel antes de retomar.')}}finally{inFlight.current=false}
  }
  void tick();const timer=setInterval(tick,2000);return()=>{disposed=true;clearInterval(timer)};
 },[enabled,authorization,demo,connectionOnly]);
 async function connect(useSaved:boolean){setStarting(true);setMessage('Abrindo a conexão com a impressora…');try{await connectKitchenPrinter(useSaved);setConnected(printerAvailable());setMessage('Conectada. Imprima um teste e depois ative os pedidos automáticos.')}catch(e){setMessage((e as Error).message)}finally{setStarting(false)}}
 async function connectBLE(){setStarting(true);setMessage('Escolha a TC-163 na lista de dispositivos BLE…');try{await connectBlePrinter(service||characteristic?{service,characteristic}:undefined);setConnected(printerAvailable());setMessage('BLE conectada. Imprima um teste e confira o papel antes de ativar.')}catch(e){setMessage((e as Error).message)}finally{setDiagnostic(bleDiagnostic());setStarting(false)}}
 async function activate(){if(enabled){setEnabled(false);setMessage('Impressão pausada.');return}setStarting(true);try{if(!since.current){const r=await fetch('/api/local-print',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${authorization}`},body:JSON.stringify({type:'arm',deviceId:device.current,claimToken:crypto.randomUUID()}),signal:AbortSignal.timeout(12000)});const d=await r.json() as {since?:string;error?:string};if(!r.ok||!d.since)throw Error(d.error||'Não foi possível ativar. Confira a conexão com a internet.');since.current=d.since}setEnabled(true);setMessage('Ativada. Os novos pedidos serão enviados à impressora.')}catch(e){setMessage((e as Error).message)}finally{setStarting(false)}}
 return <div className="auto-kitchen-printer"><div><strong><Printer size={18}/> {connectionOnly?'Conexão direta neste aparelho':'Impressão automática'}</strong><p role="status">{message}</p></div><button className="text-button printer-configure" aria-expanded={expanded} onClick={()=>setExpanded(!expanded)}>{expanded?'Fechar':'Configurar'}</button>{expanded&&<>
 {supported?<div className="auto-printer-actions">{!connected?<>{platform!=='ios'&&<><button className="outline" disabled={demo||starting} onClick={()=>connect(true)}>{starting?'Conectando…':'Conectar / reconectar'}</button><button className="outline" disabled={demo||starting} onClick={()=>connect(false)}>Escolher impressora</button></>}{ble&&<button className="primary" disabled={demo||starting} onClick={connectBLE}>Conectar por Bluetooth BLE</button>}</>:<><button className="outline" disabled={starting||enabled} onClick={async()=>{setStarting(true);try{await printKitchenReceipt('test','MAESTRIA BEACH\nTESTE DE CONEXAO\nSe este texto saiu, a conexao funciona.');setMessage('Teste enviado. Confira se o papel saiu antes de ativar.')}catch(e){setMessage((e as Error).message)}finally{setStarting(false)}}}>Imprimir teste</button><button className="text-button" disabled={starting||enabled} onClick={async()=>{try{await disconnectKitchenPrinter();setConnected(false);setMessage('Desconectada. Agora você pode conectá-la em outro aparelho.')}catch(e){setMessage((e as Error).message)}}}>Desconectar</button></>}{!connectionOnly&&<button className={enabled?'outline':'primary'} disabled={!connected||demo||starting} onClick={activate}>{enabled?<Pause size={16}/>:<Printer size={16}/>} {enabled?'Pausar':'Ativar automático'}</button>}</div>:<div className="printer-device-guide"><strong>{platform==='ios'?'Impressão a partir da cozinha':'Abra em um navegador compatível'}</strong><p>{platform==='ios'?'Para conectar neste iPhone, instale Bluefy ou WebBLE, abra o Maestria nele e permita Bluetooth. A TC-163 precisa oferecer BLE; se tiver apenas Bluetooth Classic, use o MacBook como central de impressão.':'No Android, use a opção RawBT em Imprimir comanda para conectar pelo aplicativo. A conexão direta abaixo só funciona se o navegador e a impressora oferecerem uma API compatível.'}</p></div>}
 {platform==='ios'&&<div className="printer-device-guide"><strong>Imprimir neste iPhone</strong><p>Abra o site no Bluefy ou WebBLE. Desconecte a impressora do MacBook e de outros apps, escolha Conectar por Bluetooth BLE, imprima um teste e ative. Deixe a cozinha em primeiro plano e a tela ligada. A compatibilidade BLE da TC-163 ainda precisa do teste físico.</p><a href="https://apps.apple.com/app/id1492822055" target="_blank" rel="noreferrer">Instalar Bluefy</a></div>}
 {ble&&<details><summary>Configuração avançada BLE</summary><p>Use somente UUIDs de impressão confirmados pelo fabricante ou por um diagnóstico. A detecção automática usa perfis comuns ESC/POS; não envia comandos para canais desconhecidos.</p><label>UUID do serviço<input value={service} onChange={e=>setService(e.target.value)} placeholder="Ex.: ff00" disabled={connected||starting}/></label><label>UUID de escrita<input value={characteristic} onChange={e=>setCharacteristic(e.target.value)} placeholder="Ex.: ff02" disabled={connected||starting}/></label>{diagnostic&&<pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{diagnostic}</pre>}</details>}
 {platform==='android'&&<p className="printer-browser-info">{browserInfo} · {supported?'API de conexão disponível':'Conexão direta indisponível'}</p>}<details open={platform==='ios'||!supported}><summary>Como conectar a TC-163</summary><ol><li>Ligue a impressora e pareie nas configurações Bluetooth do aparelho que ficará na cozinha.</li><li>Feche aplicativos de impressão e desconecte a TC-163 dos outros aparelhos, incluindo o MacBook, antes de conectar no Android.</li><li>Se nenhum seletor abrir no Android, confira Configurações → Aplicativos → Chrome → Permissões → Dispositivos próximos. Permita Bluetooth (os nomes variam conforme o aparelho) e feche/reabra o Chrome.</li><li>No Chrome atualizado do Android ou Chrome/Edge do notebook, toque em Escolher impressora. Selecione o nome da TC-163 e confirme na janela do navegador.</li><li>Toque em Imprimir teste, confira o papel e depois em Ativar automático.</li><li>Mantenha a cozinha aberta nesse aparelho. Os garçons podem usar Android ou iPhone para enviar pedidos.</li></ol><p>Se a lista estiver vazia mesmo depois do pareamento, este aparelho/navegador pode não expor o serviço da impressora. No Android, o botão Imprimir comanda oferece RawBT e Open ESC/POS, com abertura por toque. No iPhone, tente BLE pelo Bluefy/WebBLE; se a TC-163 não oferecer BLE, use o aparelho conectado na cozinha.</p><p>Somente pedidos recebidos depois de ativar são impressos automaticamente. Após atualizar a página, reconecte e ative novamente. Envio confirmado pelo navegador não garante que o papel saiu: confira o teste físico.</p></details></>}</div>;
}
