'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {ArrowRight,ArrowUpRight,Waves,Sun,Check,Plus,Minus,ChevronDown,Armchair,ChefHat,ReceiptText,ScanLine,Smartphone,Package,Bell,WifiOff,CheckCheck,ChartNoAxesCombined,UtensilsCrossed,GlassWater,Send,Split,Clock3} from 'lucide-react';
import './landing.css';

const signup='/painel?cadastro=1';
function Brand(){return <Link prefetch={false} className="lp-brand" href="/" aria-label="Maestria Beach, início"><span><Waves size={25}/></span><div>maestria<small>BEACH</small></div></Link>}
function CTA({children='Criar minha barraca',light=false}:{children?:React.ReactNode;light?:boolean}){return <Link prefetch={false} className={`lp-cta${light?' lp-cta-light':''}`} href={signup}>{children}<ArrowUpRight size={19}/></Link>}
const benefits=[
 {icon:Armchair,title:'Cada mesa, tudo no lugar.',text:'O garçom anota no celular. Produtos, preços e observações vão para a mesa certa.'},
 {icon:Bell,title:'Pronto para servir. Sem gritar.',text:'O pedido chega na cozinha. Um toque em “pronto” avisa o garçom para buscar.'},
 {icon:Split,title:'A conta fecha sem confusão.',text:'Divida a conta, ajuste os 10% e veja quanto falta receber. Sem juntar papelada.'},
 {icon:Package,title:'Acabou? A equipe fica sabendo.',text:'Acompanhe o consumo e o estoque. Pause o produto que acabou para evitar novos pedidos.'},
 {icon:WifiOff,title:'O sinal caiu? O pedido fica.',text:'Depois de carregar a barraca, anote mesmo sem sinal. Os pedidos seguem quando a internet volta.'},
 {icon:ChartNoAxesCombined,title:'Enxergue como foi o seu dia.',text:'Veja vendas, mesas abertas e pedidos em andamento. Saiba como a operação está indo.'},
];
const faqs=[
 ['Preciso comprar computador ou equipamento?','Você pode começar com os celulares da equipe e usar outro celular na cozinha para acompanhar os pedidos. O painel também funciona no computador. Impressora é opcional e precisa ter uma conexão compatível.'],
 ['Minha equipe vai conseguir usar?','O fluxo segue o atendimento que a equipe já conhece: escolher a mesa, tocar nos itens, adicionar observações e enviar. Cada funcionário recebe um link e acessa as funções do seu trabalho.'],
 ['Como coloco meu cardápio no sistema?','Você pode cadastrar os produtos ou enviar uma foto do cardápio para o leitor com IA. Antes de adicionar, confira os nomes, preços e categorias sugeridos. Depois, ajuste o que precisar.'],
 ['O que acontece se a internet cair?','Com a barraca carregada previamente, o garçom pode guardar pedidos no próprio aparelho. O sistema mostra os pedidos pendentes e tenta enviar quando a conexão volta. A cozinha só recebe depois da sincronização; evite repetir o pedido em outro celular.'],
 ['Dá para imprimir os pedidos?','Sim, há integração para impressão com equipamentos e navegadores compatíveis. A conexão depende do modelo da impressora e do aparelho. No iPhone, a conexão direta BLE requer um navegador auxiliar compatível. Você também pode usar a cozinha no celular, sem impressora.'],
 ['O sistema recebe o pagamento do cliente?','O caixa registra a forma de pagamento, pagamentos parciais, descontos e o fechamento da mesa. A cobrança é feita por você, usando sua maquininha, Pix ou dinheiro. O Maestria não substitui esses meios nem emite documento fiscal.'],
 ['Posso configurar do jeito da minha barraca?','Sim. Personalize os dados da barraca, mesas ou lugares, nomes, numeração, ambientes, cardápio, equipe e percentual de serviço. Você pode ajustar essas informações depois.'],
];

function PhonePreview(){return <div className="lp-phone" aria-label="Prévia ilustrativa das mesas"><div className="lp-phone-top"><span>9:41</span><span className="lp-phone-camera"/><span>••• ▰</span></div><div className="lp-phone-content"><div className="lp-phone-venue"><Sun size={14}/> Barraca do Sol <span>⋮</span></div><div className="lp-phone-title"><h3>Mesas</h3><span><Plus size={15}/></span></div><p>Um toque para começar a atender.</p><div className="lp-mini-filter"><strong>Todas</strong><span>Livres</span><span>Ocupadas</span></div><div className="lp-mini-tables">{['01','02','03','04'].map((n,i)=><div key={n} className={i%2===0?'lp-mini-occupied':''}><small><i/>{i%2===0?'Em atendimento':'Disponível'}</small><span>MESA</span><b>{n}</b><footer>{i%2===0?i===0?'R$ 89,00':'R$ 42,00':'Abrir mesa'}<ArrowUpRight size={12}/></footer></div>)}</div><div className="lp-phone-alert"><CheckCheck size={18}/><div><strong>Mesa 08 · pedido pronto</strong><span>É só pegar e servir.</span></div></div></div><div className="lp-phone-nav"><span><Armchair/>Mesas</span><span><ChefHat/>Cozinha</span><span><ReceiptText/>Caixa</span></div><div className="lp-phone-home"/></div>}

function OrderDemo(){
 const [tab,setTab]=useState(0),[quantity,setQuantity]=useState(2),[sent,setSent]=useState(false),[ready,setReady]=useState(false),[paid,setPaid]=useState(false);
 const total=65+quantity*12;
 const currency=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 return <div className="lp-demo" id="demonstracao"><div className="lp-demo-tabs" role="tablist" aria-label="Conheça as telas do sistema">{[{name:'No atendimento',icon:Smartphone},{name:'Na cozinha',icon:ChefHat},{name:'No caixa',icon:ReceiptText}].map(({name,icon:Icon},i)=><button key={name} role="tab" id={`demo-tab-${i}`} aria-controls={`demo-panel-${i}`} aria-selected={tab===i} tabIndex={tab===i?0:-1} onKeyDown={e=>{const next=e.key==='ArrowRight'?(tab+1)%3:e.key==='ArrowLeft'?(tab+2)%3:e.key==='Home'?0:e.key==='End'?2:null;if(next!==null){e.preventDefault();setTab(next);document.getElementById(`demo-tab-${next}`)?.focus()}}} onClick={()=>setTab(i)}><Icon size={18}/><span>{name}</span><b>0{i+1}</b></button>)}</div><div className="lp-demo-body" role="tabpanel" id={`demo-panel-${tab}`} aria-labelledby={`demo-tab-${tab}`}>
 <div className="lp-demo-copy" key={`copy-${tab}`}><span className="lp-eyebrow">{['UM PEDIDO, POUCOS TOQUES','TODO MUNDO NA MESMA PÁGINA','FECHAMENTO SEM QUEBRA-CABEÇA'][tab]}</span><h3>{['Anotou. Enviou. Seguiu o atendimento.','O pedido chega claro. O preparo flui.','Tudo o que a mesa consumiu. Tudo ali.'][tab]}</h3><p>{['Escolha a mesa, toque nos produtos e escreva aquela observação do cliente. A cozinha recebe sem precisar decifrar a letra de ninguém.','Itens, quantidades e observações na mesma tela. Quando estiver pronto, um toque avisa o garçom.','Confira o consumo, ajuste o serviço e registre os pagamentos. Se a turma quiser dividir, você acompanha o que falta receber.'][tab]}</p><div className="lp-demo-tip"><span><ArrowRight size={17}/></span>{['Toque em + e envie seu primeiro pedido.','Marque como pronto e veja o próximo passo.','Confira a divisão e simule o recebimento.'][tab]}</div><small>Teste à vontade. Esta demonstração não envia pedidos reais.</small></div>
 <div className="lp-demo-screen" key={`screen-${tab}`}><header><span><Sun size={16}/> Barraca do Sol</span><span className="lp-example-badge">DEMONSTRAÇÃO</span></header><div className="lp-demo-screen-inner">{tab===2&&ready&&<div className="lp-ready-feedback" role="status"><Bell size={15}/> Garçom avisado: mesa 08 pronta para servir.</div>}<div className="lp-demo-screen-heading"><div><small>{['NOVO PEDIDO','PEDIDO #008','FECHAR CONTA'][tab]}</small><h4>Mesa 08</h4></div><span className="lp-demo-status">{tab===0?'Em atendimento':tab===1?ready?'Pronto para servir':sent?'Recebido':'Prévia do pedido':paid?'Recebimento registrado':'Conferir consumo'}</span></div>
 {tab===0?<><div className="lp-demo-item"><span className="lp-food-icon"><UtensilsCrossed/></span><div><strong>Isca de peixe</strong><small>Porção · R$ 65,00</small></div><b>1×</b></div><div className="lp-demo-item"><span className="lp-food-icon lp-drink"><GlassWater/></span><div><strong>Água de coco</strong><small>Unidade · R$ 12,00</small></div><div className="lp-demo-stepper"><button disabled={sent||quantity<=1} onClick={()=>setQuantity(quantity-1)} aria-label="Retirar uma água de coco"><Minus size={14}/></button><span aria-live="polite">{quantity}</span><button disabled={sent||quantity>=9} onClick={()=>setQuantity(quantity+1)} aria-label="Adicionar uma água de coco"><Plus size={14}/></button></div></div><div className="lp-order-note">Observação: peixe sem pimenta, por favor.</div><button className="lp-demo-action" onClick={()=>{setSent(true);setTab(1)}}><Send size={16}/>{sent?'Ver pedido na cozinha':'Enviar para a cozinha'}<span>{currency(total)}</span></button></>:tab===1?<><div className="lp-kitchen-lines"><p><b>1×</b> Isca de peixe</p><p><b>{quantity}×</b> Água de coco</p></div><div className="lp-order-note"><strong>Atenção à observação</strong>Peixe sem pimenta, por favor.</div><div className="lp-demo-wait"><Clock3 size={15}/> Atendimento: Ana · Mesa 08</div><button className="lp-demo-action" onClick={()=>{setSent(true);setReady(true);setTab(2)}}><CheckCheck size={18}/>{ready?'Ver fechamento':'Marcar como pronto'}<ArrowRight size={17}/></button></>:<><div className="lp-bill-line"><span>1× Isca de peixe</span><b>R$ 65,00</b></div><div className="lp-bill-line"><span>{quantity}× Água de coco</span><b>{currency(quantity*12)}</b></div><div className="lp-bill-total"><span>Total sem serviço</span><b>{currency(total)}</b></div><div className="lp-split-preview"><Split size={19}/><div><strong>Dividindo entre 2 pessoas</strong><span>{currency(total/2)} para cada uma</span></div></div><button className="lp-demo-action" onClick={()=>setPaid(true)} disabled={paid}><Check size={17}/>{paid?'Pronto! Exemplo de conta fechada.':'Simular recebimento'}</button>{paid&&<button className="lp-demo-reset" onClick={()=>{setPaid(false);setReady(false);setSent(false);setQuantity(2);setTab(0)}}>Experimentar de novo <ArrowRight size={13}/></button>}</>}
 </div></div></div></div>;
}

export default function LandingPage(){
 useEffect(()=>{
  // Keep previously shared employee links working after the public home changes.
  if(new URLSearchParams(location.hash.slice(1)).has('access')){location.replace('/painel'+location.hash);return;}
  if(!('IntersectionObserver' in window))return;
  const root=document.querySelector('.lp');
  const connection=(navigator as Navigator & {connection?:{saveData?:boolean}}).connection;
  if(connection?.saveData)root?.classList.add('lp-save-data');
  const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches || connection?.saveData;
  const observer=new IntersectionObserver(entries=>entries.forEach(e=>{
   if(e.isIntersecting){e.target.classList.add('lp-visible');observer.unobserve(e.target)}
  }),{threshold:.06});
  if(!reduce)document.querySelectorAll('.lp-reveal').forEach(node=>{
   // Content above the fold never waits for an animation to become readable.
   if(node.getBoundingClientRect().top>window.innerHeight){node.classList.add('lp-observed');observer.observe(node)}
  });
  const activity=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('lp-in-view',e.isIntersecting)));
  document.querySelectorAll('.lp-hero-visual,.lp-scanner').forEach(node=>activity.observe(node));
  return()=>{observer.disconnect();activity.disconnect()};
 },[]);
 return <div className="lp lp-compact"><a className="lp-skip" href="#conteudo">Pular para o conteúdo</a><header className="lp-nav"><div className="lp-container lp-nav-inner"><Brand/><nav className="lp-menu" aria-label="Navegação principal"><a href="#beneficios">Benefícios</a><a href="#como-funciona">Como funciona</a><a href="#duvidas">Dúvidas</a></nav><Link prefetch={false} className="lp-entry" href="/painel">Entrar <ArrowUpRight size={16}/></Link></div></header>
 <main id="conteudo" className="lp-main">
 <section className="lp-hero lp-container" aria-label="Apresentação do Maestria Beach"><div className="lp-hero-copy"><div className="lp-hero-eyebrow"><span><Sun size={15}/></span> FEITO PARA QUEM VIVE DE PRAIA</div><h1>Praia cheia.<br/><span>Operação leve.</span></h1><p>O sistema que conecta <strong>garçom, cozinha e caixa.</strong><br/> Menos pedidos perdidos. Mais tempo para atender bem.</p><div className="lp-hero-buttons"><CTA/><a className="lp-text-link" href="#demonstracao">Testar um pedido <ArrowRight size={17}/></a></div><div className="lp-hero-points"><span><Check size={14}/> Feito para celular</span><span><Check size={14}/> Comece com sua equipe</span></div></div><div className="lp-hero-visual"><Image className="lp-beach-photo" src="/images/maestria-praia-light.webp" width="1280" height="853" alt="Mesas e guarda-sóis à beira de um mar azul" fetchPriority="high" loading="eager" sizes="(max-width: 600px) 100vw, (max-width: 1280px) 90vw, 1200px"/><div className="lp-image-label"><Waves size={19}/><span>O pé na areia.<br/><em>O controle na mão.</em></span></div><div className="lp-floating-note"><span><CheckCheck size={17}/></span><div><strong>Pedido na cozinha.</strong><small>Sem ir e voltar para avisar.</small></div></div><PhonePreview/><a className="lp-visual-caption" href="#como-funciona">CONHEÇA SEU NOVO DIA A DIA <ArrowRight size={16}/></a></div></section>
 <section className="lp-section lp-container" id="beneficios"><div className="lp-benefits-heading lp-reveal"><div className="lp-section-title"><span className="lp-eyebrow">MENOS IMPROVISO. MAIS CONTROLE.</span><h2>Menos correria.<br/><span>Mais controle da barraca.</span></h2></div></div><div className="lp-benefit-grid">{benefits.map(({icon:Icon,title,text},i)=><article className="lp-benefit lp-reveal" key={title}><span className={`lp-benefit-icon lp-tone-${i%3}`}><Icon size={23}/></span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="lp-quick-start"><ScanLine size={23}/><p><strong>Seu cardápio pronto com menos digitação.</strong> Envie uma foto, confira os itens que a IA leu e adicione.</p></div></section>
 <section className="lp-section lp-workflow" id="como-funciona"><div className="lp-container"><div className="lp-section-title lp-centered lp-reveal"><span className="lp-eyebrow">EXPERIMENTE AQUI</span><h2>Da mesa ao caixa.<br/><span>Simples assim.</span></h2><p>Toque nos botões e veja o pedido acontecer.</p></div><OrderDemo/></div></section>
 <section className="lp-section lp-container lp-faq" id="duvidas"><div className="lp-section-title lp-reveal"><span className="lp-eyebrow">PODE PERGUNTAR.</span><h2>Antes de começar.</h2></div><div className="lp-faq-list">{faqs.filter((_,i)=>[0,3,4].includes(i)).map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={19}/></summary><p>{a}</p></details>)}</div></section>
 <section className="lp-closing lp-container lp-reveal"><div><span className="lp-eyebrow">PRONTO PARA ORGANIZAR SUA BARRACA?</span><h2>Sua próxima comanda<br/><span>pode ser mais simples.</span></h2><p>Crie sua conta, cadastre o cardápio e as mesas.<br/>Compartilhe o acesso com a equipe e comece.</p><CTA/><Link prefetch={false} className="lp-closing-login" href="/painel">Já tem conta? Entre no seu painel <ArrowRight size={14}/></Link></div><div className="lp-closing-sun" aria-hidden="true"><Sun/><Waves/></div></section>
 </main><footer className="lp-footer lp-container"><div><Brand/><p>Tecnologia para quem faz a praia acontecer.</p></div><div className="lp-footer-links"><a href="#como-funciona">Conhecer o sistema</a><Link prefetch={false} href="/painel">Acessar meu painel <ArrowUpRight size={14}/></Link></div><div className="lp-footer-bottom"><span>© {new Date().getFullYear()} Maestria Beach</span><span>Feito para o ritmo da praia. <Sun size={13}/></span></div></footer></div>;
}
