'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {ArrowRight,ArrowUpRight,Waves,Sun,Check,Plus,Minus,Menu,X,ChevronDown,Armchair,ChefHat,ReceiptText,ScanLine,Smartphone,Package,Bell,WifiOff,Users,CheckCheck,ChartNoAxesCombined,Printer,UtensilsCrossed,GlassWater,Send,ShieldCheck,Split,Clock3} from 'lucide-react';
import './landing.css';

const signup='/painel?cadastro=1';
function Brand(){return <Link className="lp-brand" href="/" aria-label="Maestria Beach, início"><span><Waves size={25}/></span><div>maestria<small>BEACH</small></div></Link>}
function CTA({children='Criar minha barraca',light=false}:{children?:React.ReactNode;light?:boolean}){return <Link className={`lp-cta${light?' lp-cta-light':''}`} href={signup}>{children}<ArrowUpRight size={19}/></Link>}
const benefits=[
 {icon:ChartNoAxesCombined,title:'Seu dia em números, sem adivinhar.',text:'Confira as vendas registradas, as mesas em atendimento e os pedidos em andamento no resumo da barraca.'},
 {icon:Armchair,title:'Cada mesa, uma conta organizada.',text:'Veja o que está livre, quem está sendo atendido e quanto cada mesa consumiu. Sem procurar a comanda no meio da correria.'},
 {icon:Bell,title:'Ficou pronto? O garçom fica sabendo.',text:'A cozinha marca o pedido como pronto e o atendimento recebe o aviso. Menos idas para perguntar, mais atenção ao cliente.'},
 {icon:Split,title:'“Pode dividir?” Pode, sim.',text:'Divida o valor da conta, registre pagamentos parciais e confira o que ainda falta. Com taxa de serviço opcional.'},
 {icon:Package,title:'Saiba o que está saindo.',text:'Acompanhe o consumo e o estoque dos produtos controlados. Pause um item que acabou para evitar novos pedidos dele.'},
 {icon:WifiOff,title:'A internet oscilou? Anote mesmo assim.',text:'Depois de abrir a barraca com internet, guarde pedidos no aparelho. Eles são enviados quando a conexão volta.'},
 {icon:ReceiptText,title:'O preço certo vai junto do pedido.',text:'Os produtos e preços vêm do seu cardápio. O caixa reúne o consumo e permite ajustar descontos e serviço no fechamento.'},
 {icon:Printer,title:'Cozinha na tela. Comanda no papel.',text:'Acompanhe pedidos pelo celular ou use a impressão com equipamentos compatíveis. Escolha o que funciona para sua operação.'},
 {icon:Users,title:'Cada pessoa sabe o que fazer.',text:'Compartilhe um acesso com cada funcionário. Garçom, cozinha e caixa entram na tela certa para a função deles.'},
];
const faqs=[
 ['Preciso comprar computador ou equipamento?','Você pode começar com os celulares da equipe e usar outro celular na cozinha para acompanhar os pedidos. O painel também funciona no computador. Impressora é opcional e precisa ter uma conexão compatível.'],
 ['Minha equipe vai conseguir usar?','O fluxo segue o atendimento que a equipe já conhece: escolher a mesa, tocar nos itens, adicionar observações e enviar. Cada funcionário recebe um link e acessa as funções do seu trabalho.'],
 ['Como coloco meu cardápio no sistema?','Você pode cadastrar os produtos ou enviar uma foto do cardápio para o leitor com IA. Antes de adicionar, confira os nomes, preços e categorias sugeridos. Depois, ajuste o que precisar.'],
 ['O que acontece se a internet cair?','Com a barraca carregada previamente, o garçom pode guardar pedidos no próprio aparelho. O sistema mostra os pedidos pendentes e tenta enviar quando a conexão volta. A cozinha só recebe depois da sincronização; evite repetir o pedido em outro celular.'],
 ['Dá para imprimir os pedidos?','Sim, há integração para impressão com equipamentos e navegadores compatíveis. A conexão depende do modelo da impressora e do aparelho. No iPhone, a conexão direta BLE requer um navegador auxiliar compatível. Você também pode usar a cozinha no celular, sem impressora.'],
 ['O sistema recebe o pagamento do cliente?','O caixa registra a forma de pagamento, pagamentos parciais, descontos e o fechamento da mesa. A cobrança é feita por você, usando sua maquininha, Pix ou dinheiro. O Maestria não substitui esses meios nem emite documento fiscal.'],
 ['Posso configurar do jeito da minha barraca?','Sim. Personalize os dados da barraca, mesas ou lugares, nomes, numeração, ambientes, cardápio, equipe e percentual de serviço. Você pode ajustar essas informações depois.'],
];

function PhonePreview(){return <div className="lp-phone" aria-label="Prévia ilustrativa das mesas"><div className="lp-phone-top"><span>9:41</span><span className="lp-phone-camera"/><span>••• ▰</span></div><div className="lp-phone-content"><div className="lp-phone-venue"><Sun size={14}/> Barraca do Sol <span>⋮</span></div><div className="lp-phone-title"><h3>Mesas</h3><span><Plus size={15}/></span></div><p>Um toque para começar a atender.</p><div className="lp-mini-filter"><strong>Todas</strong><span>Livres</span><span>Ocupadas</span></div><div className="lp-mini-tables">{['01','02','03','04'].map((n,i)=><div key={n} className={i%2===0?'lp-mini-occupied':''}><small><i/>{i%2===0?'Em atendimento':'Disponível'}</small><span>MESA</span><b>{n}</b><footer>{i%2===0?i===0?'R$ 89,00':'R$ 42,00':'Abrir mesa'}<ArrowUpRight size={12}/></footer></div>)}</div><div className="lp-phone-alert"><CheckCheck size={18}/><div><strong>Mesa 08 · pedido pronto</strong><span>É só pegar e servir.</span></div></div></div><div className="lp-phone-nav"><span><Armchair/>Mesas</span><span><ChefHat/>Cozinha</span><span><ReceiptText/>Caixa</span></div><div className="lp-phone-home"/></div>}

function OrderDemo(){
 const [tab,setTab]=useState(0),[quantity,setQuantity]=useState(2),[sent,setSent]=useState(false),[ready,setReady]=useState(false),[paid,setPaid]=useState(false);
 const total=65+quantity*12;
 const currency=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 return <div className="lp-demo" id="demonstracao"><div className="lp-demo-tabs" role="tablist" aria-label="Conheça as telas do sistema">{[{name:'No atendimento',icon:Smartphone},{name:'Na cozinha',icon:ChefHat},{name:'No caixa',icon:ReceiptText}].map(({name,icon:Icon},i)=><button key={name} role="tab" id={`demo-tab-${i}`} aria-controls={`demo-panel-${i}`} aria-selected={tab===i} tabIndex={tab===i?0:-1} onKeyDown={e=>{const next=e.key==='ArrowRight'?(tab+1)%3:e.key==='ArrowLeft'?(tab+2)%3:e.key==='Home'?0:e.key==='End'?2:null;if(next!==null){e.preventDefault();setTab(next);document.getElementById(`demo-tab-${next}`)?.focus()}}} onClick={()=>setTab(i)}><Icon size={18}/><span>{name}</span><b>0{i+1}</b></button>)}</div><div className="lp-demo-body" role="tabpanel" id={`demo-panel-${tab}`} aria-labelledby={`demo-tab-${tab}`}>
 <div className="lp-demo-copy" key={`copy-${tab}`}><span className="lp-eyebrow">{['UM PEDIDO, POUCOS TOQUES','TODO MUNDO NA MESMA PÁGINA','FECHAMENTO SEM QUEBRA-CABEÇA'][tab]}</span><h3>{['Anotou. Enviou. Seguiu o atendimento.','O pedido chega claro. O preparo flui.','Tudo o que a mesa consumiu. Tudo ali.'][tab]}</h3><p>{['Escolha a mesa, toque nos produtos e escreva aquela observação do cliente. A cozinha recebe sem precisar decifrar a letra de ninguém.','Itens, quantidades e observações na mesma tela. Quando estiver pronto, um toque avisa o garçom.','Confira o consumo, ajuste o serviço e registre os pagamentos. Se a turma quiser dividir, você acompanha o que falta receber.'][tab]}</p><div className="lp-demo-tip"><span><ArrowRight size={17}/></span>{['Experimente montar e enviar o pedido ao lado.','Marque como pronto e veja o próximo passo.','Uma prévia de como a conta fica organizada.'][tab]}</div><small>Demonstração interativa com dados fictícios.</small></div>
 <div className="lp-demo-screen" key={`screen-${tab}`}><header><span><Sun size={16}/> Barraca do Sol</span><span className="lp-example-badge">DEMONSTRAÇÃO</span></header><div className="lp-demo-screen-inner"><div className="lp-demo-screen-heading"><div><small>{['NOVO PEDIDO','PEDIDO #008','FECHAR CONTA'][tab]}</small><h4>Mesa 08</h4></div><span className="lp-demo-status">{tab===0?'Em atendimento':tab===1?ready?'Pronto para servir':sent?'Recebido':'Prévia do pedido':paid?'Recebimento registrado':'Conferir consumo'}</span></div>
 {tab===0?<><div className="lp-demo-item"><span className="lp-food-icon"><UtensilsCrossed/></span><div><strong>Isca de peixe</strong><small>Porção · R$ 65,00</small></div><b>1×</b></div><div className="lp-demo-item"><span className="lp-food-icon lp-drink"><GlassWater/></span><div><strong>Água de coco</strong><small>Unidade · R$ 12,00</small></div><div className="lp-demo-stepper"><button disabled={sent||quantity<=1} onClick={()=>setQuantity(quantity-1)} aria-label="Retirar uma água de coco"><Minus size={14}/></button><span aria-live="polite">{quantity}</span><button disabled={sent||quantity>=9} onClick={()=>setQuantity(quantity+1)} aria-label="Adicionar uma água de coco"><Plus size={14}/></button></div></div><div className="lp-order-note">Observação: peixe sem pimenta, por favor.</div><button className="lp-demo-action" onClick={()=>{setSent(true);setTab(1)}}><Send size={16}/>{sent?'Ver pedido na cozinha':'Enviar para a cozinha'}<span>{currency(total)}</span></button></>:tab===1?<><div className="lp-kitchen-lines"><p><b>1×</b> Isca de peixe</p><p><b>{quantity}×</b> Água de coco</p></div><div className="lp-order-note"><strong>Atenção à observação</strong>Peixe sem pimenta, por favor.</div><div className="lp-demo-wait"><Clock3 size={15}/> Atendimento: Ana · Mesa 08</div><button className="lp-demo-action" onClick={()=>{setSent(true);setReady(true);setTab(2)}}><CheckCheck size={18}/>{ready?'Ver fechamento':'Marcar como pronto'}<ArrowRight size={17}/></button></>:<><div className="lp-bill-line"><span>1× Isca de peixe</span><b>R$ 65,00</b></div><div className="lp-bill-line"><span>{quantity}× Água de coco</span><b>{currency(quantity*12)}</b></div><div className="lp-bill-total"><span>Total sem serviço</span><b>{currency(total)}</b></div><div className="lp-split-preview"><Split size={19}/><div><strong>Dividindo entre 2 pessoas</strong><span>{currency(total/2)} para cada uma</span></div></div><button className="lp-demo-action" onClick={()=>setPaid(true)} disabled={paid}><Check size={17}/>{paid?'Pronto! Exemplo de conta fechada.':'Simular recebimento'}</button>{paid&&<button className="lp-demo-reset" onClick={()=>{setPaid(false);setReady(false);setSent(false);setQuantity(2);setTab(0)}}>Experimentar de novo <ArrowRight size={13}/></button>}</>}
 </div></div></div></div>;
}

export default function LandingPage(){
 const [menu,setMenu]=useState(false);
 useEffect(()=>{
  // Keep previously shared employee links working after the public home changes.
  if(new URLSearchParams(location.hash.slice(1)).has('access')){location.replace('/painel'+location.hash);return;}
  const nodes=document.querySelectorAll('.lp-reveal');
  if(!('IntersectionObserver' in window))return;
  const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('lp-visible');observer.unobserve(e.target)}}),{threshold:.08});
  nodes.forEach(node=>{node.classList.add('lp-observed');observer.observe(node)});return()=>observer.disconnect();
 },[]);
 return <div className="lp"><a className="lp-skip" href="#conteudo">Pular para o conteúdo</a><header className="lp-nav"><div className="lp-container lp-nav-inner"><Brand/><nav aria-label="Navegação principal" className={menu?'lp-menu lp-menu-open':'lp-menu'}><a href="#como-funciona" onClick={()=>setMenu(false)}>Como funciona</a><a href="#beneficios" onClick={()=>setMenu(false)}>O que muda</a><a href="#duvidas" onClick={()=>setMenu(false)}>Dúvidas</a><Link className="lp-mobile-login" href="/painel">Já sou cliente <ArrowUpRight size={15}/></Link></nav><div className="lp-nav-actions"><Link className="lp-login" href="/painel">Entrar <ArrowUpRight size={15}/></Link><CTA>Começar agora</CTA><button className="lp-menu-toggle" aria-label={menu?'Fechar menu':'Abrir menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div></header>
 <main id="conteudo" className="lp-main">
 <section className="lp-hero lp-container"><div className="lp-hero-copy"><div className="lp-hero-eyebrow"><span><Sun size={15}/></span> FEITO PARA QUEM VIVE DE PRAIA</div><h1>Sua barraca<br/>cheia.<br/><span>Sua cabeça<br/> tranquila.</span></h1><p>Do primeiro pedido à conta fechada.<br/>Garçom, cozinha e caixa conectados em um sistema simples, direto no celular.</p><div className="lp-hero-buttons"><CTA/><a className="lp-text-link" href="#demonstracao">Ver na prática <ArrowRight size={17}/></a></div><div className="lp-hero-points"><span><Check size={14}/> Feito para celular</span><span><Check size={14}/> Sem papelada</span></div></div><div className="lp-hero-visual"><Image className="lp-beach-photo" src="/images/maestria-praia.webp" width="1536" height="1024" alt="Mesas e guarda-sóis à beira de um mar azul" fetchPriority="high" loading="eager" sizes="(max-width: 600px) 100vw, (max-width: 1100px) 50vw, 640px"/><div className="lp-image-label"><Waves size={19}/><span>Mais leveza.<br/>Até no dia mais cheio.</span></div><div className="lp-floating-note"><span><CheckCheck size={17}/></span><div><strong>Pedido na cozinha.</strong><small>Sem ir e voltar para avisar.</small></div></div><PhonePreview/><span className="lp-visual-caption">UMA PRÉVIA DO SEU NOVO DIA A DIA</span></div></section>
 <div className="lp-proof-strip"><div className="lp-container"><span>Da areia ao caixa.<br/><strong>Tudo conversa.</strong></span><p><Smartphone/> Atendimento no celular</p><p><ChefHat/> Cozinha organizada</p><p><ReceiptText/> Conta fácil de conferir</p><p><Waves/> Mais controle para você</p></div></div>
 <section className="lp-section lp-container lp-pain lp-reveal"><div className="lp-section-title"><span className="lp-eyebrow">VOCÊ CONHECE ESSA CORRERIA.</span><h2>Dia cheio é bom.<br/><span>Confusão não precisa vir junto.</span></h2><p>O cliente quer aproveitar a praia. Sua equipe quer atender bem. O Maestria ajuda a deixar o caminho entre os dois mais simples.</p></div><div className="lp-pain-grid">{[
 ['“Cadê o pedido da mesa 8?”','O pedido fica registrado.','Itens, observações e andamento visíveis para quem precisa.'],
 ['“Isso estava na comanda?”','O consumo fica na mesa certa.','Tudo reunido para conferir a conta sem juntar anotações.'],
 ['“Acabou e ninguém me avisou.”','A equipe vê o que pode vender.','Disponibilidade e estoque ajudam a evitar pedidos de itens que acabaram.'],
 ].map(([pain,title,text],i)=><article key={pain}><span className="lp-pain-number">0{i+1}</span><p className="lp-pain-quote">{pain}</p><div className="lp-pain-arrow"><ArrowDown/></div><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="lp-section lp-workflow" id="como-funciona"><div className="lp-container"><div className="lp-section-title lp-centered lp-reveal"><span className="lp-eyebrow">SIMPLES PARA QUEM USA. BOM PARA QUEM GERE.</span><h2>Um pedido. Uma equipe.<br/><span>Todo mundo conectado.</span></h2><p>Veja como o atendimento anda da mesa até o caixa.<br/>Pode tocar: essa demonstração é sua.</p></div><OrderDemo/></div></section>
 <section className="lp-section lp-container" id="beneficios"><div className="lp-benefits-heading lp-reveal"><div className="lp-section-title"><span className="lp-eyebrow">MENOS IMPROVISO. MAIS CONTROLE.</span><h2>Os detalhes que<br/><span>mudam o seu dia.</span></h2></div><p>Do “mais uma água” ao “fecha a conta”,<br/>cada etapa tem seu lugar.</p></div><div className="lp-benefit-grid">{benefits.map(({icon:Icon,title,text},i)=><article className="lp-benefit lp-reveal" key={title}><span className={`lp-benefit-icon lp-tone-${i%3}`}><Icon size={23}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section className="lp-container lp-scanner lp-reveal"><div className="lp-scanner-art"><div className="lp-scan-paper"><span className="lp-paper-sun"><Sun size={30}/></span><small>BARRACA DO SOL</small><h3>Nosso cardápio</h3><div><span>Isca de peixe</span><b>65,00</b></div><div><span>Água de coco</span><b>12,00</b></div><div><span>Batata frita</span><b>35,00</b></div><p>Feito para saborear sem pressa.</p><div className="lp-scan-beam"/></div><span className="lp-scan-corner lp-corner-tl"/><span className="lp-scan-corner lp-corner-br"/><div className="lp-scan-result"><span><ScanLine size={21}/></span><div><strong>Seu cardápio, digital.</strong><small>Confira os itens e pronto.</small></div><Check size={19}/></div></div><div className="lp-scanner-copy"><span className="lp-eyebrow">SEU CARDÁPIO JÁ ESTÁ PRONTO. APROVEITE ELE.</span><h2>Uma foto.<br/><span>Menos digitação.</span></h2><p>Envie uma foto do seu cardápio. A inteligência artificial lê os itens e sugere o cadastro. Você confere os nomes e preços antes de adicionar.</p><div className="lp-scan-steps"><span><b>1</b> Fotografe</span><ArrowRight size={14}/><span><b>2</b> Confira</span><ArrowRight size={14}/><span><b>3</b> Adicione</span></div><Link className="lp-text-link" href={signup}>Quero organizar meu cardápio <ArrowUpRight size={18}/></Link></div></section>
 <section className="lp-section lp-setup"><div className="lp-container"><div className="lp-section-title lp-centered lp-reveal"><span className="lp-eyebrow">DO JEITO DA SUA BARRACA.</span><h2>Comece com o que você tem.<br/><span>Organize do seu jeito.</span></h2><p>Uma barraca pequena ou uma praia de mesas.<br/>Você configura sua operação, sem complicar a rotina.</p></div><div className="lp-setup-grid">{[{icon:Sun,title:'Apresente sua barraca',text:'Nome, praia, contatos e informações do seu espaço.'},{icon:Armchair,title:'Monte sua operação',text:'Cardápio, mesas, áreas e taxa de serviço. Tudo ajustável.'},{icon:Users,title:'Chame sua equipe',text:'Crie os acessos, compartilhe os links e comece a atender.'}].map(({icon:Icon,title,text},i)=><article key={title} className="lp-reveal"><div><Icon size={23}/><span>0{i+1}</span></div><h3>{title}</h3><p>{text}</p></article>)}</div><div className="lp-setup-cta"><CTA light/><span><ShieldCheck size={16}/> Conta com e-mail e senha. Simples assim.</span></div></div></section>
 <section className="lp-section lp-container lp-faq" id="duvidas"><div className="lp-section-title lp-reveal"><span className="lp-eyebrow">PODE PERGUNTAR.</span><h2>Sem dúvida.<br/><span>Sem complicação.</span></h2><p>O que você precisa saber antes de colocar sua barraca no Maestria.</p><span className="lp-faq-mark"><Waves size={76}/></span></div><div className="lp-faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={19}/></summary><p>{a}</p></details>)}</div></section>
 <section className="lp-closing lp-container lp-reveal"><div><span className="lp-eyebrow">O PRÓXIMO DIA DE PRAIA PODE SER MAIS LEVE.</span><h2>Cuide dos clientes.<br/><span>A organização vai com a gente.</span></h2><p>Seu atendimento merece mais do que papel solto<br/>e informação desencontrada.</p><CTA/><Link className="lp-closing-login" href="/painel">Já tem conta? Entre no seu painel <ArrowRight size={14}/></Link></div><div className="lp-closing-sun" aria-hidden="true"><Sun/><Waves/></div></section>
 </main><footer className="lp-footer lp-container"><div><Brand/><p>Tecnologia para quem faz a praia acontecer.</p></div><div className="lp-footer-links"><a href="#como-funciona">Conhecer o sistema</a><Link href="/painel">Acessar meu painel <ArrowUpRight size={14}/></Link></div><div className="lp-footer-bottom"><span>© {new Date().getFullYear()} Maestria Beach</span><span>Feito para o ritmo da praia. <Sun size={13}/></span></div></footer><div className="lp-mobile-cta"><span>Seu atendimento,<br/><strong>mais organizado.</strong></span><CTA>Começar agora</CTA></div></div>;
}

function ArrowDown(){return <ArrowRight size={18} style={{transform:'rotate(90deg)'}}/>}
