'use client';
import {useState} from 'react';
import {Search,Plus,Minus,ArrowLeft,Check,ShoppingBag} from 'lucide-react';
import {Product,money} from '@/lib/domain';
export default function OrderComposer({products,cart,setCart,notes,setNotes,note,setNote,busy,onSend}:{products:Product[];cart:Record<string,number>;setCart:(v:Record<string,number>)=>void;notes:Record<string,string>;setNotes:(v:Record<string,string>)=>void;note:string;setNote:(v:string)=>void;busy:boolean;onSend:()=>Promise<void>}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('Todos'),[review,setReview]=useState(false);
 const selected=products.filter(p=>cart[p.id]>0),count=selected.reduce((n,p)=>n+cart[p.id],0),total=selected.reduce((n,p)=>n+p.price*cart[p.id],0);
 const normalize=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const filtered=products.filter(p=>p.available&&p.stock!==0&&(category==='Todos'||p.category===category)&&normalize(p.name+' '+p.description).includes(normalize(query)));
 const quantity=(p:Product)=><div className="stepper"><button disabled={busy||!cart[p.id]} aria-label={'Remover '+p.name} onClick={()=>setCart({...cart,[p.id]:Math.max(0,(cart[p.id]||0)-1)})}><Minus size={18}/></button><b key={cart[p.id]||0} aria-live="polite">{cart[p.id]||0}</b><button disabled={busy||cart[p.id]>=99||!p.available||p.stock!=null&&(cart[p.id]||0)>=p.stock} aria-label={'Adicionar '+p.name} onClick={()=>setCart({...cart,[p.id]:Math.min(99,(cart[p.id]||0)+1)})}><Plus size={18}/></button></div>;
 return <section className="order-composer"><div className="composer-heading"><div><small>{review?'ÚLTIMA CONFERIDA':'NOVO PEDIDO'}</small><h2>{review?'Está tudo certo?':'O que vamos servir?'}</h2></div>{review&&<button className="outline" disabled={busy} onClick={()=>setReview(false)}><ArrowLeft size={16}/> Cardápio</button>}</div>{!review?<><div className="search"><Search size={20}/><input aria-label="Buscar no cardápio" placeholder="Digite um prato ou uma bebida" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="category-chips">{['Todos',...new Set(products.filter(p=>p.available).map(p=>p.category))].map(c=><button aria-pressed={category===c} className={category===c?'selected':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="composer-products">{filtered.map(p=><article className={'composer-product '+(cart[p.id]?'in-cart':'')} key={p.id}><div className="product-copy"><small>{p.category} · {p.station==='bar'?'Bar':'Cozinha'}</small><h3>{p.name}</h3>{p.description&&<p>{p.description}</p>}<strong>{money(p.price)}</strong>{p.stock!=null&&p.stock<=(p.lowStock??5)&&<small className="stock-inline">{p.stock} unidades disponíveis</small>}</div>{quantity(p)}</article>)}</div>{!filtered.length&&<p className="muted">Nenhum item encontrado. Tente outra busca ou categoria.</p>}</>:<><p className="muted">Confira as quantidades e escreva os detalhes de cada item.</p>{selected.map(p=><article className="review-product" key={p.id}><div><h3>{p.name}</h3><strong>{money(p.price*cart[p.id])}</strong></div>{quantity(p)}{!p.available&&<p role="alert">Este item ficou indisponível. Remova para continuar.</p>}<label className="field"><span>Detalhes de {p.name}</span><input disabled={busy} maxLength={200} placeholder="Ex.: sem cebola, bem passado…" value={notes[p.id]||''} onChange={e=>setNotes({...notes,[p.id]:e.target.value})}/></label></article>)}<label className="field"><span>Observação do pedido inteiro</span><textarea disabled={busy} maxLength={500} placeholder="Ex.: trazer as bebidas primeiro" value={note} onChange={e=>setNote(e.target.value)}/></label></>}
 <div className="composer-dock"><div><span>{count} {count===1?'item':'itens'}</span><strong>{money(total)}</strong></div><button className="primary" disabled={!count||busy||(review&&selected.some(p=>!p.available))} onClick={()=>review?onSend():setReview(true)}>{review?<Check size={20}/>:<ShoppingBag size={20}/>} {busy?'Enviando…':review?'Enviar pedido':'Revisar pedido'}</button></div></section>
}
