'use client';
import {useState} from 'react';
import {Printer,CheckCircle2,Clock,AlertCircle,Copy,RefreshCw,Wifi} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {State,Action} from '@/lib/domain';
import {toast} from 'sonner';
import ReceiptPrintButton from './receipt-print-button';
export default function PrinterPanel({state,demo,owner,authorization,mutate}:{state:State;demo:boolean;owner:boolean;authorization:string;mutate:(a:Omit<Action,'id'> & {id?:string},message?:string)=>Promise<boolean>}){
 const [credentials,setCredentials]=useState<{username:string;password:string;path:string}|null>(null),[busy,setBusy]=useState(false),[reprint,setReprint]=useState<string|null>(null);
 const connected=!!state.printer?.lastSeen&&Date.now()-Date.parse(state.printer.lastSeen)<45000;
 const jobs=(state.printJobs||[]).slice().reverse();const pending=jobs.filter(j=>['queued','printing'].includes(j.status)).length;
 async function pair(){if(demo){toast('Crie sua barraca para conectar uma impressora real.');return}setBusy(true);try{const r=await fetch('/api/printer',{method:'POST',headers:{'Content-Type':'application/json',...(authorization?{Authorization:`Bearer ${authorization}`}:{})}});const d=await r.json() as {username:string;password:string;path:string;error?:string};if(!r.ok)throw Error(d.error);setCredentials(d)}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <div className="printer-panel"><div className="printer-setup"><h3>TC-163 · Bluetooth direto</h3><p>Na Cozinha, conecte a impressora e ative a impressão automática. Cada novo pedido é enviado sem tocar no celular.</p><ol><li>Pareie a TC-163 nas configurações Bluetooth.</li><li>Use Chrome atualizado no Android (138+) ou Chrome/Edge no notebook.</li><li>Abra a Cozinha, toque em Conectar impressora e depois Ativar.</li></ol><p>No iPhone, este Bluetooth não está disponível ao site. Para esse aparelho, use uma impressora de rede compatível.</p><p className="muted">Alternativa manual para Android antigo: Open ESC/POS Print Service, impressora padrão e papel de 58 mm.</p><a className="outline full" href="https://play.google.com/store/apps/details?id=com.farminos.print" target="_blank" rel="noopener noreferrer">Instalar aplicativo de impressão</a><ReceiptPrintButton content={state.name+'\nTESTE DE IMPRESSAO\nTC-163 · 58 mm\n1x Camarao\nOBS: sem sal\nCOMANDA NAO FISCAL\n\n\n'}/><p className="muted">O aplicativo faz a conexão Bluetooth. Enviar a comanda não confirma a saída do papel; confira antes de enviar outra via.</p></div><details className="printer-setup"><summary>Impressora de rede · Star CloudPRNT</summary><div className={'printer-health '+(connected?'online':'')}><span className="printer-health-icon"><Printer size={25}/></span><div><strong>{connected?'Impressora conectada':'Conecte a impressora da cozinha'}</strong><p>{connected?state.printer?.deviceStatus:'Star com CloudPRNT · rede Ethernet'}</p></div><span className="device-dot"/></div><div className="automation-switch"><div><strong>Imprimir ao enviar pedido</strong><p>A comanda sai sem tocar em imprimir.</p></div><Switch aria-label="Impressão automática" checked={state.printer?.enabled||false} disabled={!owner||busy} onCheckedChange={enabled=>mutate({type:'printer',enabled},enabled?'Impressão automática ativada. Conecte o equipamento para receber a fila.':'Impressão automática pausada.')}/></div>{!connected&&<div className="print-notice"><AlertCircle size={17}/><p>Os pedidos ficam guardados na fila enquanto a impressora está desconectada. Não houve impressão física confirmada.</p></div>}
 {owner&&<details className="printer-setup"><summary>Configurar conexão <Wifi size={16}/></summary><ol><li>Conecte a Star mC-Print3 com CloudPRNT à rede e atualize o firmware para 3.2 ou superior.</li><li>No painel da impressora, ative CloudPRNT e configure a URL, usuário e senha abaixo. Use consulta a cada 5 segundos.</li><li>Ative a impressão automática e envie uma comanda de teste.</li></ol><p className="muted">O endereço precisa ser HTTPS público e acessível pela impressora. A prévia localhost e uma hospedagem com login obrigatório não recebem a conexão externa.</p><button className="outline full" disabled={busy} onClick={pair}>{credentials?'Gerar nova conexão':'Gerar dados de conexão'}</button><small>Gerar uma nova conexão invalida a senha anterior.</small>{credentials&&<div className="pairing-data">{[['URL',location.origin+credentials.path],['Usuário',credentials.username],['Senha',credentials.password]].map(([label,value])=><label key={label}><span>{label}</span><div><input readOnly type={label==='Senha'?'password':'text'} value={value}/><button aria-label={'Copiar '+label} onClick={async()=>{try{await navigator.clipboard.writeText(value);toast.success(label+' copiado.')}catch{toast.error('Copie o valor do campo.')}}}><Copy size={16}/></button></div></label>)}<small>Guarde a senha agora. Ela não será exibida novamente.</small></div>}</details>}
 <div className="print-queue-title"><h3>Fila de impressão</h3><span>{pending} pendentes</span></div>{!jobs.length?<div className="print-empty"><CheckCircle2 size={23}/><p>Os próximos pedidos aparecem aqui automaticamente.</p></div>:<div className="print-jobs">{jobs.slice(0,15).map(j=><div className="print-job" key={j.id}><div className={'print-job-icon '+j.status}>{j.status==='printed'?<CheckCircle2 size={18}/>:j.status==='failed'||j.status==='uncertain'?<AlertCircle size={18}/>:<Clock size={18}/>}</div><div><strong>{j.orderId==='test'?'Teste de impressão':'Pedido #'+j.orderId.slice(-6).toUpperCase()}</strong><span>{({queued:'Na fila',printing:'Enviada · aguardando confirmação',printed:'Impressão confirmada',sent:'Enviada por Bluetooth · confira o papel',failed:'Não impressa',uncertain:'Verificar impressão'})[j.status]}</span>{j.error&&<p>{j.error}</p>}{reprint===j.id?<div className="reprint-confirm"><p>Confira o papel: uma nova via pode duplicar o preparo.</p><button className="outline" disabled={busy} onClick={async()=>{if(await mutate({type:'reprint',jobId:j.id},'Nova via adicionada à fila.'))setReprint(null)}}>Enviar nova via</button><button className="text-button" onClick={()=>setReprint(null)}>Voltar</button></div>:!['queued','printing'].includes(j.status)&&<button className="text-button" onClick={()=>setReprint(j.id)}><RefreshCw size={12}/> Reimprimir</button>}</div></div>)}</div>}{owner&&<button className="primary full" disabled={busy||demo} onClick={()=>mutate({type:'printTest'},'Comanda de teste adicionada à fila.')}><Printer size={17}/> Enviar teste automático</button>}<p className="printer-footnote">Só aparece “Impressão confirmada” quando o equipamento responde. Sem confirmação, confira a comanda antes de pedir outra via.</p></details></div>
}
