'use client';
import {VenueProfile} from '@/lib/domain';
import {useState} from 'react';
import {ArrowLeft,ArrowRight,Check,MapPin,Sun,Armchair} from 'lucide-react';
export type SetupData={profile:VenueProfile;team:{name:string;role:string}[];name:string;location:string;phone:string;count:number;prefix:string;start:number;area:string;service:number};
export default function VenueSetup({busy,onComplete}:{busy:boolean;onComplete:(data:SetupData)=>Promise<void>}){
 const [step,setStep]=useState(0),[data,setData]=useState<SetupData>({profile:{kind:'Barraca de praia',address:'',reference:'',hours:'',instagram:''},team:[],name:'',location:'',phone:'',count:12,prefix:'Mesa',start:1,area:'Areia',service:10});
 const update=(key:keyof SetupData,value:string|number)=>setData(d=>({...d,[key]:value}));
 const names=Array.from({length:Math.min(4,Math.max(0,data.count))},(_,i)=>`${data.prefix} ${String(data.start+i).padStart(2,'0')}`);
 return <div className="venue-setup"><div className="setup-progress" aria-label={`Etapa ${step+1} de 4`}>{['Barraca','Espaço','Equipe','Revisão'].map((name,i)=><div className={i<=step?'current':''} key={name}><span>{i<step?<Check size={15}/>:i+1}</span><small>{name}</small></div>)}</div><form onSubmit={async e=>{e.preventDefault();if(step<3)setStep(step+1);else await onComplete(data)}}><div className="setup-step" key={step}>
 {step===0&&<><div className="setup-symbol"><Sun/></div><h2>Vamos dar nome ao seu lugar.</h2><p>Comece pelo básico. Você pode editar depois.</p><label className="field"><span>Tipo de estabelecimento</span><select value={data.profile.kind} onChange={e=>setData({...data,profile:{...data.profile,kind:e.target.value}})}>{['Barraca de praia','Quiosque','Beach club','Restaurante'].map(k=><option key={k}>{k}</option>)}</select></label><label className="field"><span>Nome da barraca</span><input autoFocus required maxLength={100} value={data.name} placeholder="Ex.: Barraca do Sol" onChange={e=>update('name',e.target.value)}/></label><label className="field"><span>Praia e cidade</span><input required maxLength={150} value={data.location} placeholder="Ex.: Praia do Futuro, Fortaleza" onChange={e=>update('location',e.target.value)}/></label><label className="field"><span>Telefone da barraca <small>opcional</small></span><input type="tel" maxLength={25} value={data.phone} placeholder="(85) 99999-9999" onChange={e=>update('phone',e.target.value)}/></label><details className="setup-extra"><summary>Endereço, horário e redes sociais <small>opcional</small></summary>{([['address','Endereço completo',200],['reference','Ponto de referência',150],['hours','Dias e horários de funcionamento',150],['instagram','Instagram',80]] as const).map(([key,label,max])=><label className="field" key={key}><span>{label}</span><input maxLength={max} value={data.profile[key]} onChange={e=>setData({...data,profile:{...data.profile,[key]:e.target.value}})}/></label>)}</details></>}
 {step===2&&<><div className="setup-symbol"><Sun/></div><h2>Quem vai trabalhar com você?</h2><p>Cadastre a equipe agora ou continue para adicionar depois. Os links individuais ficam na página Equipe.</p>{data.team.map((person,i)=><div className="setup-person" key={i}><label className="field"><span>Nome da pessoa</span><input required maxLength={100} value={person.name} onChange={e=>setData({...data,team:data.team.map((p,j)=>i===j?{...p,name:e.target.value}:p)})}/></label><label className="field"><span>Função</span><select value={person.role} onChange={e=>setData({...data,team:data.team.map((p,j)=>i===j?{...p,role:e.target.value}:p)})}><option value="waiter">Garçom</option><option value="kitchen">Cozinha</option><option value="cashier">Caixa</option></select></label><button type="button" className="text-button" onClick={()=>setData({...data,team:data.team.filter((_,j)=>i!==j)})}>Remover pessoa</button></div>)}<button type="button" className="outline full" disabled={data.team.length>=50} onClick={()=>setData({...data,team:[...data.team,{name:'',role:'waiter'}]})}>+ Adicionar pessoa</button>{!data.team.length&&<p className="muted">Tudo bem começar sozinho. Você tem acesso a todas as funções.</p>}</>}
 {step===1&&<><div className="setup-symbol"><Armchair/></div><h2>Organize do seu jeito.</h2><p>Vamos criar os lugares automaticamente. Depois você pode renomear cada um.</p><label className="field"><span>Como você chama os lugares?</span><select value={data.prefix} onChange={e=>update('prefix',e.target.value)}><option>Mesa</option><option>Guarda-sol</option><option>Quiosque</option></select></label><div className="form-columns"><label className="field"><span>Quantidade</span><input type="number" min={1} max={300} required value={data.count||''} onChange={e=>update('count',Number(e.target.value))}/></label><label className="field"><span>Começar no número</span><input type="number" min={1} max={9999} required value={data.start||''} onChange={e=>update('start',Number(e.target.value))}/></label></div><label className="field"><span>Ambiente</span><input required maxLength={40} value={data.area} placeholder="Areia, deck, salão…" onChange={e=>update('area',e.target.value)}/></label><div className="setup-preview" aria-label="Prévia dos lugares">{names.map(n=><span key={n}>{n}</span>)}{data.count>4&&<small>+ {data.count-4} lugares</small>}</div><label className="field"><span>Serviço sugerido (%)</span><input type="number" min={0} max={30} required value={data.service} onChange={e=>update('service',Number(e.target.value))}/></label><p className="muted">Use 0 para não sugerir taxa. O caixa pode retirar o serviço ao fechar a conta.</p></>}
 {step===3&&<><div className="setup-symbol"><Check/></div><h2>Pronto para começar?</h2><p>Confira os detalhes. Seu próximo passo será montar o cardápio.</p><div className="setup-review"><h3>{data.name}</h3><p><MapPin size={16}/>{data.location}</p>{data.phone&&<p>{data.phone}</p>}<dl><div><dt>Estabelecimento</dt><dd>{data.profile.kind}</dd></div><div><dt>Equipe inicial</dt><dd>{data.team.length} {data.team.length===1?'pessoa':'pessoas'}</dd></div>{data.profile.hours&&<div><dt>Funcionamento</dt><dd>{data.profile.hours}</dd></div>}<div><dt>Lugares</dt><dd>{data.count} · {data.prefix}</dd></div><div><dt>Numeração</dt><dd>{data.start} a {data.start+data.count-1}</dd></div><div><dt>Ambiente</dt><dd>{data.area}</dd></div><div><dt>Serviço opcional</dt><dd>{data.service}%</dd></div></dl></div></>}
 </div><div className="setup-actions">{step>0&&<button type="button" className="outline" disabled={busy} onClick={()=>setStep(step-1)}><ArrowLeft size={17}/> Voltar</button>}<button className="primary full" disabled={busy}>{busy?'Criando sua barraca…':step===3?'Criar minha barraca':'Continuar'}{step===3?<Check size={18}/>:<ArrowRight size={18}/>}</button></div></form></div>
}
