import {database,readVenue,saveVenue} from '@/lib/db';
import {accountDefaults,applyBilling,canAdmin,type BillingAction} from '@/lib/saas-billing';
import type {State} from '@/lib/domain';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store, private'}});
async function admin(req:Request){const token=req.headers.get('authorization')?.replace(/^Bearer /,'');if(!token)return null;const {data:{user},error}=await database().auth.getUser(token);if(error||!user||!canAdmin(user.id,process.env.SAAS_ADMIN_USER_IDS||''))return null;return user}
function summary(owner:string,state:State){const orders=state.orders.filter(o=>o.status!=='cancelled'),events=[...orders.map(o=>o.createdAt),...state.payments.map(p=>p.createdAt)].sort();const today=new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});return {owner,name:state.name,location:state.location,phone:state.phone||'',profile:state.profile,tables:state.tables.length,occupied:state.tables.filter(t=>t.session).length,products:state.products.length,employees:state.employees.filter(e=>e.active).length,orders:orders.length,sales:state.payments.reduce((n,p)=>n+p.total,0),salesToday:state.payments.filter(p=>new Date(p.createdAt).toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'})===today).reduce((n,p)=>n+p.total,0),lastActivity:events.at(-1)||null,saas:accountDefaults(state.saas)}}
export async function GET(req:Request){try{const user=await admin(req);if(!user)return json({error:'Acesso exclusivo do administrador do SaaS.'},403);const db=database();const users=[];for(let page=1;;page++){const {data,error}=await db.auth.admin.listUsers({page,perPage:1000});if(error)throw Error('Não foi possível listar os donos.');users.push(...data.users.map(u=>({id:u.id,email:u.email||'',createdAt:u.created_at,lastSignIn:u.last_sign_in_at||null})));if(data.users.length<1000)break}const venues=[];for(let from=0;;from+=500){const {data,error}=await db.from('venues').select('owner,state').order('owner').range(from,from+499);if(error)throw Error('Não foi possível listar as barracas.');venues.push(...data.map(v=>summary(v.owner,v.state as State)));if(data.length<500)break}return json({me:{email:user.email},users,venues,generatedAt:new Date().toISOString()})}catch(e){return json({error:(e as Error).message},400)}}
export async function POST(req:Request){try{const user=await admin(req);if(!user)return json({error:'Acesso exclusivo do administrador do SaaS.'},403);const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return json({error:'Origem inválida.'},403);if(Number(req.headers.get('content-length')||0)>12000)return json({error:'Solicitação muito grande.'},413);const body=await req.json() as BillingAction&{owner:string};if(!/^[0-9a-f-]{36}$/i.test(body.owner||''))throw Error('Barraca inválida.');for(let attempt=0;attempt<5;attempt++){const row=await readVenue(body.owner);if(!row)throw Error('Barraca não encontrada.');const updated=applyBilling(row.state.saas,body,user.email||user.id);row.state.saas=updated;if(await saveVenue(body.owner,row.version,row.state))return json({venue:summary(body.owner,row.state)})}return json({error:'Esta barraca foi atualizada por outra pessoa. Tente novamente.'},409)}catch(e){return json({error:(e as Error).message},400)}}
