import {ticket,type PrintJob,type PrinterState} from './printing.ts';
export type Role='owner'|'waiter'|'kitchen'|'cashier';
export type Product={id:string;name:string;category:string;price:number;description:string;available:boolean;station:'kitchen'|'bar'};
export type Table={id:string;name:string;area:string;session:string|null;closing:boolean};
export type Line={productId:string;name:string;price:number;quantity:number;station:string};
export type Order={id:string;tableId:string;session:string;lines:Line[];note:string;status:'new'|'preparing'|'ready'|'delivered'|'cancelled';createdAt:string;author:string};
export type Payment={id:string;session:string;tableName:string;subtotal:number;service:number;discount:number;total:number;method:string;createdAt:string};
export type Employee={id:string;name:string;role:Exclude<Role,'owner'>;active:boolean};
export type State={printJobs?:PrintJob[];printer?:PrinterState;name:string;location:string;service:number;tables:Table[];products:Product[];orders:Order[];payments:Payment[];employees:Employee[];processed:string[]};
export type Action={id:string;type:string;[key:string]:unknown};
export const money=(c:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100);
export const orderTotal=(o:Order)=>o.lines.reduce((s,l)=>s+l.price*l.quantity,0);
export const tableOrders=(s:State,t:Table)=>s.orders.filter(o=>!!t.session&&o.session===t.session&&o.status!=='cancelled');
export const subtotal=(s:State,t:Table)=>tableOrders(s,t).reduce((v,o)=>v+orderTotal(o),0);
function str(v:unknown,max=100){if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw Error('Preencha os campos corretamente.');return v.trim()}
function int(v:unknown,min:number,max:number){if(typeof v!=='number'||!Number.isInteger(v)||v<min||v>max)throw Error('Confira os valores informados.');return v}
const roles:Record<string,Role[]>={order:['owner','waiter'],status:['owner','kitchen','waiter'],closing:['owner','waiter','cashier'],reopen:['owner','cashier'],checkout:['owner','cashier'],product:['owner'],availability:['owner'],table:['owner'],settings:['owner'],employee:['owner'],revoke:['owner'],cancel:['owner'],printer:['owner'],reprint:['owner','kitchen'],printTest:['owner']};
export function createState(name:string,location:string,count:number):State{return {name:str(name),location:location.slice(0,150),service:10,tables:Array.from({length:int(count,1,300)},(_,i)=>({id:crypto.randomUUID(),name:`Mesa ${String(i+1).padStart(2,'0')}`,area:'Areia',session:null,closing:false})),products:[],orders:[],payments:[],employees:[],processed:[]}}
export function applyAction(state:State,a:Action,role:Role,author:string,now=new Date().toISOString()):State{
 if(!roles[a.type]?.includes(role))throw Error('Seu acesso não permite essa ação.');str(a.id,100);if(state.processed.includes(a.id))return state;
 const s=structuredClone(state);const table=()=>{const t=s.tables.find(x=>x.id===a.tableId);if(!t)throw Error('Mesa não encontrada.');return t};
 switch(a.type){
 case 'order':{const t=table();if(t.closing)throw Error('Esta conta está em fechamento. Reabra no caixa para adicionar pedidos.');if(!Array.isArray(a.items)||a.items.length<1||a.items.length>100)throw Error('Selecione os itens do pedido.');const lines:Line[]=a.items.map((x:{productId:string;quantity:number})=>{const p=s.products.find(p=>p.id===x.productId&&p.available);if(!p)throw Error('Um item não está mais disponível. Atualize o pedido.');return {productId:p.id,name:p.name,price:p.price,quantity:int(x.quantity,1,99),station:p.station}});t.session||=a.id;s.orders.push({id:a.id,tableId:t.id,session:t.session,lines,note:typeof a.note==='string'?a.note.slice(0,500):'',status:'new',createdAt:now,author});s.printJobs||=[];s.printJobs.push({id:a.id,orderId:a.id,content:ticket(s.name,t.name,s.orders[s.orders.length-1]),status:'queued',createdAt:now});break}
 case 'status':{const o=s.orders.find(o=>o.id===a.orderId);if(!o)throw Error('Pedido não encontrado.');const next={new:'preparing',preparing:'ready',ready:'delivered'}[o.status as 'new'|'preparing'|'ready'];if(a.status!==next&&!(o.status==='new'&&a.status==='ready'&&(role==='owner'||role==='kitchen')))throw Error('O pedido já foi atualizado.');if(role==='waiter'&&a.status!=='delivered')throw Error('Somente a cozinha altera o preparo.');if(role==='kitchen'&&a.status==='delivered')throw Error('O garçom confirma a entrega.');o.status=a.status as Order['status'];break}
 case 'closing':{const t=table();if(!t.session)throw Error('A mesa não tem uma conta aberta.');t.closing=true;break}
 case 'reopen':table().closing=false;break;
 case 'checkout':{const t=table();if(!t.session||!t.closing)throw Error('Solicite o fechamento antes de receber.');const active=tableOrders(s,t);if(active.some(o=>o.status!=='delivered'))throw Error('Há pedidos pendentes. Confirme a entrega ou cancele antes de fechar.');const sub=subtotal(s,t),discount=int(a.discount,0,sub),service=a.withService===true?Math.round(sub*s.service/100):0;const method=str(a.method);if(!['Pix','Dinheiro','Cartão de crédito','Cartão de débito'].includes(method))throw Error('Escolha a forma de pagamento.');s.payments.push({id:a.id,session:t.session,tableName:t.name,subtotal:sub,service,discount,total:sub+service-discount,method,createdAt:now});t.session=null;t.closing=false;break}
 case 'product':{if(!Array.isArray(a.products)||!a.products.length||a.products.length>200)throw Error('Confira os itens do cardápio.');for(const raw of a.products as Product[]){const p:Product={id:raw.id||crypto.randomUUID(),name:str(raw.name),category:str(raw.category,50),price:int(raw.price,1,10000000),description:typeof raw.description==='string'?raw.description.slice(0,300):'',available:raw.available!==false,station:raw.station==='bar'?'bar':'kitchen'};const i=s.products.findIndex(x=>x.id===p.id);if(i<0)s.products.push(p);else s.products[i]=p;}break}
 case 'availability':{const p=s.products.find(p=>p.id===a.productId);if(!p)throw Error('Item não encontrado.');p.available=a.available===true;break}
 case 'table':{const name=str(a.name,40);if(s.tables.some(t=>t.name.toLowerCase()===name.toLowerCase()&&t.id!==a.tableId))throw Error('Já existe uma mesa com esse nome.');if(a.tableId){const t=table();t.name=name;t.area=str(a.area,40)}else {if(s.tables.length>=300)throw Error('Limite de 300 mesas.');s.tables.push({id:a.id,name,area:str(a.area,40),session:null,closing:false})}break}
 case 'settings':s.name=str(a.name);s.location=str(a.location,150);s.service=int(a.service,0,30);break;
 case 'employee':{const r=a.role;if(!['waiter','kitchen','cashier'].includes(r as string))throw Error('Escolha uma função.');s.employees.push({id:a.id,name:str(a.name),role:r as Employee['role'],active:true});break}
 case 'revoke':{const e=s.employees.find(e=>e.id===a.employeeId);if(!e)throw Error('Funcionário não encontrado.');e.active=false;break}
 case 'printer':s.printer={...s.printer,enabled:a.enabled===true};break;
 case 'printTest':{s.printJobs||=[];s.printJobs.push({id:a.id,orderId:'test',content:'MAESTRIA BEACH\nTESTE DE IMPRESSAO\nConexao automatica configurada.\n\n\n',status:'queued',createdAt:now});break}
 case 'reprint':{s.printJobs||=[];const old=s.printJobs.find(j=>j.id===a.jobId);if(!old||old.status==='printing'||old.status==='queued')throw Error('Confira o status da comanda antes de reimprimir.');s.printJobs.push({id:a.id,orderId:old.orderId,content:'REIMPRESSAO - CONFERIR DUPLICIDADE\n'+old.content,status:'queued',createdAt:now});break}
 case 'cancel':{const o=s.orders.find(o=>o.id===a.orderId);if(!o||s.payments.some(p=>p.session===o.session))throw Error('Este pedido não pode ser cancelado.');if(!str(a.reason,300))throw Error('Informe o motivo.');for(const j of s.printJobs||[])if(j.orderId===o.id&&j.status==='queued'){j.status='failed';j.error='Pedido cancelado antes de imprimir.'}s.printJobs||=[];s.printJobs.push({id:a.id,orderId:o.id,content:ticket(s.name,s.tables.find(t=>t.id===o.tableId)?.name||'Mesa',{...o,note:String(a.reason)},'CANCELAMENTO'),status:'queued',createdAt:now});o.status='cancelled';o.note+=` | Cancelado: ${a.reason}`;break}
 }
 s.processed.push(a.id);return s;
}
export function demoState():State{const s=createState('Barraca do Sol','Praia do Futuro, Fortaleza • CE',12);s.products=[['Isca de peixe crocante','Porções',6800,'Peixe fresquinho, molho da casa e limão.','kitchen'],['Camarão ao alho e óleo','Porções',8900,'Camarões salteados, alho dourado e ervas.','kitchen'],['Batata frita','Porções',3200,'Douradinha, crocante e feita na hora.','kitchen'],['Água de coco','Bebidas',1000,'Natural e bem geladinha.','bar'],['Cerveja 600 ml','Bebidas',1800,'Consulte as marcas disponíveis.','bar'],['Caipirinha de limão','Drinks',2400,'Limão fresco, cachaça e gelo.','bar'],['Refrigerante lata','Bebidas',700,'Lata de 350 ml.','bar'],['Peixe inteiro frito','Pratos',12500,'Acompanha arroz, farofa e vinagrete.','kitchen']].map(([name,category,price,description,station],i)=>({id:`p${i}`,name,category,price,description,station,available:true}) as Product);[0,2,3,6,7,9].forEach((i,k)=>{const t=s.tables[i];t.session=`demo-session-${i}`;t.closing=i===7;s.orders.push({id:`demo-order-${i}`,tableId:t.id,session:t.session,lines:[{productId:'p0',name:s.products[k%3].name,price:s.products[k%3].price,quantity:1,station:'kitchen'},{productId:'p3',name:'Água de coco',price:1000,quantity:2,station:'bar'}],note:k===1?'Sem cebola, por favor.':'',status:i===7?'delivered':k===0?'ready':k%2?'preparing':'new',createdAt:new Date(Date.now()-(k+2)*60000).toISOString(),author:'Ana'});});s.employees=[{id:'ana',name:'Ana Silva',role:'waiter',active:true},{id:'pedro',name:'Pedro Santos',role:'kitchen',active:true},{id:'julia',name:'Júlia Costa',role:'cashier',active:true}];return s;}
