import assert from 'node:assert/strict';
import test from 'node:test';
import {createState,applyAction,subtotal} from '../lib/domain.ts';
const act=(s,a,role='owner')=>applyAction(s,{id:crypto.randomUUID(),...a},role,'Teste');
function fixture(){let s=createState('Teste','Praia',2);return act(s,{type:'product',products:[{id:'p',name:'Água',category:'Bebidas',price:750,station:'bar',available:true}]})}
test('pedido usa preço do servidor e retry não duplica',()=>{let s=fixture();const a={id:'unique',type:'order',tableId:s.tables[0].id,items:[{productId:'p',quantity:2,price:1}]};s=act(s,a,'waiter');assert.equal(subtotal(s,s.tables[0]),1500);s=act(s,a,'waiter');assert.equal(s.orders.length,1)});
test('caixa só fecha após entrega, serviço removível, mesa reutilizável',()=>{let s=fixture();const tableId=s.tables[0].id;s=act(s,{type:'order',tableId,items:[{productId:'p',quantity:3}]});const orderId=s.orders[0].id;s=act(s,{type:'closing',tableId});assert.throws(()=>act(s,{type:'checkout',tableId,withService:false,discount:0,method:'Pix'}),/pendentes/);s=act(s,{type:'status',orderId,status:'preparing'},'kitchen');s=act(s,{type:'status',orderId,status:'ready'},'kitchen');s=act(s,{type:'status',orderId,status:'delivered'},'waiter');s=act(s,{type:'checkout',tableId,withService:false,discount:250,method:'Pix'});assert.equal(s.payments[0].total,2000);assert.equal(s.tables[0].session,null);s=act(s,{type:'order',tableId,items:[{productId:'p',quantity:1}]});assert.equal(subtotal(s,s.tables[0]),750);assert.equal(s.payments.length,1)});
test('permissões e item indisponível são validados no servidor',()=>{let s=fixture();assert.throws(()=>act(s,{type:'settings',name:'x',location:'y',service:10},'waiter'),/acesso/);s=act(s,{type:'availability',productId:'p',available:false});assert.throws(()=>act(s,{type:'order',tableId:s.tables[0].id,items:[{productId:'p',quantity:1}]},'waiter'),/disponível/)});
test('fechamento bloqueia novos pedidos e desconto inválido',()=>{let s=fixture();const tableId=s.tables[0].id;s=act(s,{type:'order',tableId,items:[{productId:'p',quantity:1}]});s=act(s,{type:'closing',tableId});assert.throws(()=>act(s,{type:'order',tableId,items:[{productId:'p',quantity:1}]}),/fechamento/);for(const status of ['preparing','ready','delivered'])s=act(s,{type:'status',orderId:s.orders[0].id,status});assert.throws(()=>act(s,{type:'checkout',tableId,discount:1000,method:'Pix',withService:true}),/valores/);s=act(s,{type:'checkout',tableId,discount:0,method:'Pix',withService:true});assert.equal(s.payments[0].total,825)});
test('edição do cardápio não altera preço de pedido anterior',()=>{let s=fixture();const tableId=s.tables[0].id;s=act(s,{type:'order',tableId,items:[{productId:'p',quantity:1}]});s=act(s,{type:'product',products:[{id:'p',name:'Água',category:'Bebidas',price:1200,station:'bar'}]});assert.equal(subtotal(s,s.tables[0]),750)});
test('cozinha pode marcar pronto em um toque; garçom apenas confirma entrega',()=>{let s=fixture();s=act(s,{type:'order',tableId:s.tables[0].id,items:[{productId:'p',quantity:1}]});const orderId=s.orders[0].id;assert.throws(()=>act(s,{type:'status',orderId,status:'ready'},'waiter'));s=act(s,{type:'status',orderId,status:'ready'},'kitchen');assert.equal(s.orders[0].status,'ready');assert.throws(()=>act(s,{type:'status',orderId,status:'delivered'},'kitchen'));s=act(s,{type:'status',orderId,status:'delivered'},'waiter');assert.equal(s.orders[0].status,'delivered');assert.throws(()=>act(s,{type:'status',orderId,status:'ready'},'kitchen'))});
test('cadastro completo cria lugares personalizados e valida limites',()=>{const s=createState('Barraca','Fortaleza',3,{prefix:'Guarda-sol',start:8,area:'Deck',service:0,phone:'85999999999'});assert.deepEqual(s.tables.map(t=>t.name),['Guarda-sol 08','Guarda-sol 09','Guarda-sol 10']);assert.equal(s.tables[0].area,'Deck');assert.equal(s.service,0);assert.equal(s.phone,'85999999999');assert.throws(()=>createState('Barraca','Praia',301));assert.throws(()=>createState('Barraca','Praia',2,{start:-1}));assert.throws(()=>createState('Barraca','Praia',2,{service:40}));const edited=act(s,{type:'settings',name:'Novo nome',location:'Praia',service:10,phone:''});assert.equal(edited.phone,'');assert.equal(edited.tables[0].name,'Guarda-sol 08')});
