import assert from 'node:assert/strict';
import test from 'node:test';
import {createState,applyAction,subtotal} from '../lib/domain.ts';
const act=(s,a,role='owner')=>applyAction(s,{id:crypto.randomUUID(),...a},role,'Teste');
function fixture(){let s=createState('Teste','Praia',2);return act(s,{type:'product',products:[{id:'p',name:'Água',category:'Bebidas',price:750,station:'bar',available:true}]})}
test('pedido usa preço do servidor e retry não duplica',()=>{let s=fixture();const a={id:'unique',type:'order',tableId:s.tables[0].id,items:[{productId:'p',quantity:2,price:1}]};s=act(s,a,'waiter');assert.equal(subtotal(s,s.tables[0]),1500);s=act(s,a,'waiter');assert.equal(s.orders.length,1)});
test('caixa só fecha após entrega, serviço removível, mesa reutilizável',()=>{let s=fixture();const tableId=s.tables[0].id;s=act(s,{type:'order',tableId,items:[{productId:'p',quantity:3}]});const orderId=s.orders[0].id;s=act(s,{type:'closing',tableId});assert.throws(()=>act(s,{type:'checkout',tableId,withService:false,discount:0,method:'Pix'}),/pendentes/);s=act(s,{type:'status',orderId,status:'preparing'},'kitchen');s=act(s,{type:'status',orderId,status:'ready'},'kitchen');s=act(s,{type:'status',orderId,status:'delivered'},'waiter');s=act(s,{type:'checkout',tableId,withService:false,discount:250,method:'Pix'});assert.equal(s.payments[0].total,2000);assert.equal(s.tables[0].session,null);s=act(s,{type:'order',tableId,items:[{productId:'p',quantity:1}]});assert.equal(subtotal(s,s.tables[0]),750);assert.equal(s.payments.length,1)});
test('permissões e item indisponível são validados no servidor',()=>{let s=fixture();assert.throws(()=>act(s,{type:'settings',name:'x',location:'y',service:10},'waiter'),/acesso/);s=act(s,{type:'availability',productId:'p',available:false});assert.throws(()=>act(s,{type:'order',tableId:s.tables[0].id,items:[{productId:'p',quantity:1}]},'waiter'),/disponível/)});
test('fechamento bloqueia novos pedidos e desconto inválido',()=>{let s=fixture();const tableId=s.tables[0].id;s=act(s,{type:'order',tableId,items:[{productId:'p',quantity:1}]});s=act(s,{type:'closing',tableId});assert.throws(()=>act(s,{type:'order',tableId,items:[{productId:'p',quantity:1}]}),/fechamento/);for(const status of ['preparing','ready','delivered'])s=act(s,{type:'status',orderId:s.orders[0].id,status});assert.throws(()=>act(s,{type:'checkout',tableId,discount:1000,method:'Pix',withService:true}),/valores/);s=act(s,{type:'checkout',tableId,discount:0,method:'Pix',withService:true});assert.equal(s.payments[0].total,825)});
test('edição do cardápio não altera preço de pedido anterior',()=>{let s=fixture();const tableId=s.tables[0].id;s=act(s,{type:'order',tableId,items:[{productId:'p',quantity:1}]});s=act(s,{type:'product',products:[{id:'p',name:'Água',category:'Bebidas',price:1200,station:'bar'}]});assert.equal(subtotal(s,s.tables[0]),750)});
test('cozinha pode marcar pronto em um toque; garçom apenas confirma entrega',()=>{let s=fixture();s=act(s,{type:'order',tableId:s.tables[0].id,items:[{productId:'p',quantity:1}]});const orderId=s.orders[0].id;assert.throws(()=>act(s,{type:'status',orderId,status:'ready'},'waiter'));s=act(s,{type:'status',orderId,status:'ready'},'kitchen');assert.equal(s.orders[0].status,'ready');assert.throws(()=>act(s,{type:'status',orderId,status:'delivered'},'kitchen'));s=act(s,{type:'status',orderId,status:'delivered'},'waiter');assert.equal(s.orders[0].status,'delivered');assert.throws(()=>act(s,{type:'status',orderId,status:'ready'},'kitchen'))});
test('cadastro completo cria lugares personalizados e valida limites',()=>{const s=createState('Barraca','Fortaleza',3,{prefix:'Guarda-sol',start:8,area:'Deck',service:0,phone:'85999999999'});assert.deepEqual(s.tables.map(t=>t.name),['Guarda-sol 08','Guarda-sol 09','Guarda-sol 10']);assert.equal(s.tables[0].area,'Deck');assert.equal(s.service,0);assert.equal(s.phone,'85999999999');assert.throws(()=>createState('Barraca','Praia',301));assert.throws(()=>createState('Barraca','Praia',2,{start:-1}));assert.throws(()=>createState('Barraca','Praia',2,{service:40}));const edited=act(s,{type:'settings',name:'Novo nome',location:'Praia',service:10,phone:''});assert.equal(edited.phone,'');assert.equal(edited.tables[0].name,'Guarda-sol 08')});
test('observação por item chega à cozinha e à comanda sem alterar o preço',()=>{let s=fixture();s=act(s,{type:'order',tableId:s.tables[0].id,items:[{productId:'p',quantity:2,note:'Sem gelo'}]});assert.equal(s.orders[0].lines[0].note,'Sem gelo');assert.match(s.printJobs[0].content,/OBS: Sem gelo/);assert.equal(subtotal(s,s.tables[0]),1500);assert.throws(()=>act(s,{type:'order',tableId:s.tables[0].id,items:[{productId:'p',quantity:1,note:'a'.repeat(201)}]}));});
test('cadastro salva perfil e equipe com funções válidas e mantém compatibilidade',()=>{const s=createState('Sol','Praia',3,{profile:{kind:'Quiosque',hours:'Ter a dom, 9h às 18h',address:'Av. Beira-mar'},team:[{name:'Ana',role:'waiter'},{name:'Bia',role:'kitchen'}]});assert.equal(s.profile.hours,'Ter a dom, 9h às 18h');assert.equal(s.employees.length,2);assert.equal(s.employees[0].active,true);assert.notEqual(s.employees[0].id,s.employees[1].id);assert.throws(()=>createState('Sol','Praia',1,{team:[{name:'X',role:'owner'}]}));const next=act(s,{type:'settings',name:'Sol',location:'Praia',service:10});assert.deepEqual(next.profile,s.profile);});

test('recebimentos parciais quitam centavos exatos e só liberam mesa no final',()=>{let s=fixture();const tableId=s.tables[0].id;s=act(s,{type:'order',tableId,items:[{productId:'p',quantity:1}]});s=act(s,{type:'status',orderId:s.orders[0].id,status:'ready'});s=act(s,{type:'status',orderId:s.orders[0].id,status:'delivered'});s=act(s,{type:'closing',tableId});const session=s.tables[0].session;const first={id:'part-one',type:'checkout',tableId,withService:true,discount:25,amount:267,method:'Pix',part:'Ana'};s=act(s,first);s=act(s,first);assert.equal(s.payments.length,1);assert.equal(s.tables[0].session,session);assert.throws(()=>act(s,{type:'reopen',tableId}),/saldo/);assert.throws(()=>act(s,{type:'checkout',tableId,withService:false,discount:25,amount:1,method:'Pix'}),/definidos/);assert.throws(()=>act(s,{type:'checkout',tableId,withService:true,discount:25,amount:600,method:'Pix'}));s=act(s,{type:'checkout',tableId,withService:true,discount:25,amount:267,method:'Dinheiro'});s=act(s,{type:'checkout',tableId,withService:true,discount:25,method:'Cartão de débito'});assert.equal(s.tables[0].session,null);assert.equal(s.payments.reduce((n,p)=>n+p.total,0),800);assert.equal(s.payments.reduce((n,p)=>n+p.subtotal,0),750);assert.equal(s.payments.reduce((n,p)=>n+p.service,0),75);assert.equal(s.payments.reduce((n,p)=>n+p.discount,0),25)});
test('estoque baixa sem duplicar e recusa concorrência e linhas duplicadas além do saldo',()=>{let s=fixture();s=act(s,{type:'stock',productId:'p',quantity:3,lowStock:1,reason:'Contagem'});const tableId=s.tables[0].id,a={id:'stock-order',type:'order',tableId,items:[{productId:'p',quantity:2}]};s=act(s,a);s=act(s,a);assert.equal(s.products[0].stock,1);assert.equal(s.stockMovements.length,2);assert.throws(()=>act(s,{type:'order',tableId,items:[{productId:'p',quantity:2}]}),/insuficiente/);assert.throws(()=>act(s,{type:'order',tableId,items:[{productId:'p',quantity:1},{productId:'p',quantity:1}]}),/insuficiente/);assert.throws(()=>act(s,{type:'stock',productId:'p',quantity:4,lowStock:1,reason:'x'},'waiter'));s=act(s,{type:'cancel',orderId:'stock-order',reason:'Cliente desistiu',returnStock:true});assert.equal(s.products[0].stock,3);assert.throws(()=>act(s,{type:'cancel',orderId:'stock-order',reason:'x',returnStock:true}));s=act(s,{type:'product',products:[{id:'p',name:'Água',category:'Bebidas',price:800}]});assert.equal(s.products[0].stock,3)});
test('pedido offline protege sessão e retry de resposta perdida não duplica',()=>{let s=fixture();const tableId=s.tables[0].id,a={id:'offline-1',type:'order',tableId,expectedSession:null,items:[{productId:'p',quantity:1}]};s=act(s,a);s=act(s,a);assert.equal(s.orders.length,1);assert.throws(()=>act(s,{id:'late',type:'order',tableId,expectedSession:null,items:[{productId:'p',quantity:1}]}),/mudou/);s=act(s,{id:'offline-2',type:'order',tableId,expectedSession:'offline-1',items:[{productId:'p',quantity:1}]});assert.equal(s.orders.length,2)});

test('cancelar sem devolver estoque mantém a baixa e cozinha pode pausar item',()=>{let s=fixture();s=act(s,{type:'stock',productId:'p',quantity:2,lowStock:1,reason:'Contagem'});s=act(s,{type:'order',tableId:s.tables[0].id,items:[{productId:'p',quantity:1}]});s=act(s,{type:'cancel',orderId:s.orders[0].id,reason:'Preparado e descartado'});assert.equal(s.products[0].stock,1);s=act(s,{type:'availability',productId:'p',available:false},'kitchen');assert.equal(s.products[0].available,false)});

test('recebimentos permanecem consistentes quando taxa configurada muda no meio da conta',()=>{let s=fixture();const tableId=s.tables[0].id;s=act(s,{type:'order',tableId,items:[{productId:'p',quantity:1}]});s=act(s,{type:'status',orderId:s.orders[0].id,status:'ready'});s=act(s,{type:'status',orderId:s.orders[0].id,status:'delivered'});s=act(s,{type:'closing',tableId});s=act(s,{type:'checkout',tableId,withService:true,discount:13,amount:333,method:'Pix'});s=act(s,{type:'settings',name:'Teste',location:'Praia',service:20});s=act(s,{type:'checkout',tableId,withService:true,discount:13,method:'Dinheiro'});assert.equal(s.payments.reduce((n,p)=>n+p.total,0),812);for(const p of s.payments)assert.equal(p.subtotal+p.service-p.discount,p.total)});
test('preço alterado enquanto offline exige revisão antes de cobrar',()=>{const s=fixture();assert.throws(()=>act(s,{type:'order',tableId:s.tables[0].id,expectedPrices:{p:500},items:[{productId:'p',quantity:1}]}),/preço/)});
