import test from 'node:test';
import assert from 'node:assert/strict';
import {publicWorkspace} from '../lib/workspace-view.ts';
import {createState,applyAction} from '../lib/domain.ts';
import {applyBilling,canAdmin,invoiceStatus,assertSubscription,csvCell} from '../lib/saas-billing.ts';
const now='2026-09-29T12:00:00Z';const act=(s,a)=>applyBilling(s,{id:crypto.randomUUID(),...a},'admin',now);
function fixture(){return act(undefined,{type:'subscription',plan:'Praia',monthlyFee:14900,billingDay:10,status:'active',trialUntil:'',notes:'Cliente mensal'})}
test('admin não usa e-mail nem metadados e falha fechado sem configuração',()=>{assert.equal(canAdmin('user-1',''),false);assert.equal(canAdmin('user-1','user-2'),false);assert.equal(canAdmin('user-1',' user-1,user-2 '),true);assert.equal(canAdmin('',''),false)});
test('mensalidade é única por competência e mantém valor acordado original',()=>{let s=fixture();s=act(s,{type:'generate',period:'2026-09'});s=act(s,{type:'generate',period:'2026-09'});assert.equal(s.invoices.length,1);assert.equal(s.invoices[0].amount,14900);assert.equal(s.invoices[0].dueDate,'2026-09-10');assert.equal(invoiceStatus(s.invoices[0],'2026-09-29'),'overdue');s=act(s,{type:'subscription',plan:'Novo',monthlyFee:19900,billingDay:5,status:'active',trialUntil:'',notes:''});assert.equal(s.invoices[0].amount,14900);s=act(s,{type:'generate',period:'2026-10'});assert.equal(s.invoices[1].amount,19900)});
test('recebimento manual é idempotente e reversão exige motivo com auditoria',()=>{let s=act(fixture(),{type:'generate',period:'2026-09'});const a={id:'receipt',type:'paid',invoiceId:s.invoices[0].id,paidAt:'2026-09-29',method:'Pix',receipt:'Conferido no banco'};s=act(s,a);s=act(s,a);assert.equal(s.invoices[0].status,'paid');assert.equal(s.audit.length,3);assert.throws(()=>act(s,{type:'reopen',invoiceId:s.invoices[0].id,reason:''}));s=act(s,{type:'reopen',invoiceId:s.invoices[0].id,reason:'Registro incorreto'});assert.equal(s.invoices[0].status,'pending');assert.equal(s.invoices[0].paidAt,undefined);assert.match(s.audit.at(-1).action,/Registro incorreto/)});
test('cancelamento preserva registro e impedimentos de acesso são explícitos',()=>{let s=act(fixture(),{type:'generate',period:'2026-09'});s=act(s,{type:'void',invoiceId:s.invoices[0].id,reason:'Isenção acordada'});s=act(s,{type:'generate',period:'2026-09'});assert.equal(s.invoices.length,1);assert.equal(s.invoices[0].status,'void');assertSubscription({status:'active'});assertSubscription({status:'trial',trialUntil:'2000-01-01'});assert.throws(()=>assertSubscription({status:'paused'}));assert.throws(()=>assertSubscription({status:'cancelled'}))});
test('valores, datas, status e exportação são validados',()=>{const s=fixture();assert.throws(()=>act(s,{type:'invoice',description:'X',amount:-1,dueDate:'2026-10-10'}));assert.throws(()=>act(s,{type:'invoice',description:'X',amount:100,dueDate:'2026-02-31'}));assert.throws(()=>act(s,{type:'generate',period:'2026-13'}));const invoice=act(s,{type:'invoice',description:'Instalação',amount:10000,dueDate:'2026-10-10'});assert.throws(()=>act(invoice,{type:'paid',invoiceId:invoice.invoices[0].id,paidAt:'2027-01-01',method:'Pix',receipt:''}));assert.equal(csvCell('=1+1'),'"\'=1+1"');assert.equal(csvCell('Texto; seguro'),'"Texto; seguro"')});

test('cobrança avulsa no mesmo mês não impede mensalidade',()=>{let s=act(fixture(),{type:'invoice',description:'Instalação',amount:5000,dueDate:'2026-09-30'});s=act(s,{type:'generate',period:'2026-09'});assert.equal(s.invoices.length,2);s=act(s,{type:'generate',period:'2026-09'});assert.equal(s.invoices.length,2)});

test('notas e finanças do SaaS nunca aparecem na operação dos donos ou funcionários',()=>{const state=createState('Barraca','Praia',1);state.saas=fixture();for(const role of ['owner','waiter','kitchen','cashier']){const result=publicWorkspace(state,role);assert.equal('saas' in result,false)}const next=applyAction(state,{id:'edit',type:'settings',name:'Barraca nova',location:'Praia',service:10,saas:{status:'active',monthlyFee:0}},'owner','Dono');assert.equal(next.saas.monthlyFee,14900);assert.equal(next.saas.notes,'Cliente mensal')});
