import {assertSubscription} from '@/lib/saas-billing';
import {resolveAccess} from '@/lib/access';
import {database,hashToken,readVenue,saveVenue} from '@/lib/db';
import {applyAction,createState,State,Role,Action} from '@/lib/domain';
export const dynamic='force-dynamic';
import {publicWorkspace as visible} from '@/lib/workspace-view';
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(req:Request){try{const a=await resolveAccess(req);if(!a)return response({needsSignIn:true},401);return response({state:visible(a.state,a.role),role:a.role,author:a.author})}catch(e){console.error('Workspace read failed',e);return response({error:(e as Error).message},400)}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return response({error:'Origem inválida.'},403);if(Number(req.headers.get('content-length')||0)>200000)return response({error:'Pedido muito grande.'},413);const a=await resolveAccess(req);if(!a)return response({error:'Entre na sua conta para continuar.'},401);const body=await req.json() as Action & {name:string;location:string;count:number;employeeId:string};const db=database();if(body.type==='setup'){if(a.role!=='owner')throw Error('Acesso não autorizado.');if(a.state)throw Error('Sua barraca já está cadastrada.');const state=createState(body.name,body.location||'',body.count,{phone:body.phone,prefix:body.prefix,start:body.start,area:body.area,service:body.service,profile:body.profile,team:body.team});const {error}=await db.from('venues').insert({owner:a.owner,state,version:0});if(error)throw Error('Não foi possível cadastrar a barraca. Atualize e tente novamente.');return response({state,role:a.role,author:a.author})}
 if(!a.state)throw Error('Cadastre sua barraca primeiro.');if(body.type==='invite'){if(a.role!=='owner')throw Error('Acesso não autorizado.');const employee=a.state.employees.find(e=>e.id===body.employeeId&&e.active);if(!employee)throw Error('Funcionário não encontrado.');const token=crypto.randomUUID()+crypto.randomUUID();const {error}=await db.from('accesses').upsert({hash:await hashToken(token),owner:a.owner,employee:employee.id},{onConflict:'owner,employee'});if(error)throw Error('Não foi possível gerar o acesso.');return response({token})}
 for(let attempt=0;attempt<4;attempt++){const row=await readVenue(a.owner);if(!row)throw Error('Barraca não encontrada.');const current:State=row.state;assertSubscription(current.saas);if(a.role!=='owner'&&!current.employees.some(e=>e.id===a.employeeId&&e.role===a.role&&e.active))throw Error('Acesso desativado.');const updated=applyAction(current,body,a.role,a.author);const saved=await saveVenue(a.owner,row.version,updated);if(saved)return response({state:visible(updated,a.role),role:a.role,author:a.author});}
 return response({error:'Outro atendimento atualizou esta mesa. Tente novamente.'},409);
 }catch(e){console.error('Workspace operation failed',e);return response({error:(e as Error).message||'Não foi possível salvar.'},400)}}
